### ISSUE TITLE
Schema generation - Add schema properties title and description per property

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json.Schema#1]
See https://github.com/JamesNK/Newtonsoft.Json/pull/204

**Comment by purediamox** [comment]
Hi James, 
Any update on this? Any plans to add support for description? 

I was thinking about creating a utility to inject the XML doc comments into description fields.
Great library!

**Comment by XmlmXmlmX** [comment]
I need this too.

http://stackoverflow.com/questions/14811386/adding-description-to-properties-while-generating-json-schema-using-json-net

**Comment by JamesNK** [comment]
Sorry for the delay in how long this took. This is now supported https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/87
