### ISSUE TITLE
StackOverflowException in FindSchema

### ISSUE THREAD

**Issue by JoanCharmant** [JamesNK/Newtonsoft.Json.Schema#10]
Hello,
The following schema causes a StackOverflowException on JSchema.Parse():

```javascript
{
  "type" : "object",
  "properties" : {
      "test" : {"$ref" : "#/definitions/b" }
  },

  "definitions": {
    
    "a" : {
      "type":"string"
    },
    "b": {
      "type": "object",
      "properties": {
        "b2" : { "$ref": "#definitions/a" }
      }
    }
  }
}
```

Note that one of the schema in the definitions section references another schema in definitions. The unterminated recursion appears to be in FindSchema(). 
The schema parses correctly in, for example, https://json-schema-validator.herokuapp.com/

**Comment by JamesNK** [comment]
There is an error in your schema. You are missing a forward slash after the hash for property b2:

      "properties": {
        "b2" : { "$ref": "#definitions/a" }
      }

I tested it out on that website and web given JSON with a "b2" property the schema parser fails.

I'll fix the stackoverflow error to a better error message. Thanks for letting me know.

**Comment by JamesNK** [comment]
Fixed
