### ISSUE TITLE
Using Schema to transform an object

### ISSUE THREAD

**Issue by Antaris** [JamesNK/Newtonsoft.Json.Schema#100]
Hi,

I'm looking at the feasibility of using JSON.NET Schema to map/reduce a larger JSON object into a smaller tailored object.

I'm building a data-heavy platform storing documents in Elasticsearch. Now, subscribers can have access to that data, but only a subset of the fields provided by a document depending on their subscription level, so lets say:

```
Project -> ProjectView
```

I'm built a JSON schema for my `Project` type, and what I want is to define a `ProjectView` schema, and use that to transform an instance of `Project` into `ProjectView` via the fields expressed specifically in the schema.

Is that possible?

**Comment by JamesNK** [comment]
No, JSON schema is for validation. There is no mapping involved
