### ISSUE TITLE
Description attribute not respected as of version 3.0.3

### ISSUE THREAD

**Issue by jonasbutt** [JamesNK/Newtonsoft.Json.Schema#101]
It seems descriptions do not end up in generated JSON Schema.

See: http://www.newtonsoft.com/jsonschema/help/html/GenerateWithDescriptions.htm

**Comment by JamesNK** [comment]
Hi

This unit test is still passing with 3.0.3 - https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/c37b6f7a03e11ed4ba78807cea7a4d0be8152af3/Src/Newtonsoft.Json.Schema.Tests/Documentation/Samples/Generation/GenerateWithDescriptions.cs

Are you using the correct DescriptionAttribute? There are a number of different versions from various frameworks. The correct one is System.ComponentModel.DescriptionAttribute

**Comment by dntbrsnbl** [comment]
It appears to be working in dotnet framework projects but not dotnet standard

**Comment by JamesNK** [comment]
Ok, I see what's going on. Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/0747d51869df8deeb50ff71c8e8928f92477e1e3

This will be in the next release.

**Comment by sbochoa** [comment]
Is this fix being released any time soon?

**Comment by JamesNK** [comment]
Hi

It will be released in the next week.

**Comment by JamesNK** [comment]
Available now - https://github.com/JamesNK/Newtonsoft.Json.Schema/releases/tag/3.0.4
