### ISSUE TITLE
JSchema.ToString() throws System.InvalidOperationException when used in a FormattableString

### ISSUE THREAD

**Issue by candoumbe** [JamesNK/Newtonsoft.Json.Schema#102]
Hi there !
I'm using the v3.0.3 of the Newtonsoft.Json.Schema package to validate a json string in a unit test :

```
var json = new {"field" : "firstname", op : "isnull", value : 6};
var schema = new JSchema
                    {
                        Type = JSchemaType.Object,
                        Properties =
                        {
                            ["field"] = new JSchema { Type = JSchemaType.String },
                            ["op"] = new JSchema { Type = JSchemaType.String },
                            ["value"] = new JSchema { Type = JSchemaType.None }
                        },
                        Required = { "field", "op" }
                    };


JObject.Parse(json).IsValid().Should().BeFalse(); // this line succeed

_output.WriteLine($"Testing :{json} {Environment.NewLine} against {Environment.NewLine} {schema}"); // this line throws System.InvalidOperationException
```

Here's the full stacktrace i got

> at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaTypeHelpers.MapType(JSchemaType type)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaWriter.WriteType(String propertyName, JsonWriter writer, JSchemaType type)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaWriter.WriteSchemaObjectInternal(JSchema schema)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaWriter.WriteSchemaInternal(JSchema schema)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaWriter.WriteSchemaDictionaryIfNotNull(JSchema context, JsonWriter writer, String propertyName, IDictionary`2 properties)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaWriter.WriteSchemaObjectInternal(JSchema schema)
>    at Newtonsoft.Json.Schema.Infrastructure.JSchemaWriter.WriteSchemaInternal(JSchema schema)
>    at Newtonsoft.Json.Schema.JSchema.ToStringInternal(JSchemaWriterSettings settings)
>   ...

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/2a26878986a782d9620d9d887a0983ea26f23adb

You can stop the error by not using JSchemaType.None.

```
var schema = new JSchema
                    {
                        Type = JSchemaType.Object,
                        Properties =
                        {
                            ["field"] = new JSchema { Type = JSchemaType.String },
                            ["op"] = new JSchema { Type = JSchemaType.String },
                            ["value"] = new JSchema()
                        },
                        Required = { "field", "op" }
                    };
```
