### ISSUE TITLE
JSchema.Parse strips out "title" on properties which are references

### ISSUE THREAD

**Issue by arrkaye** [JamesNK/Newtonsoft.Json.Schema#104]
Hi,

Parsing the schema:

`{"definitions":{"words":{"type":"string"},"choices":{"enum":["Yes","No"],"type":"string"}},"required":["choices"],"type":"object","properties":{"incorrect":{"$ref":"#/definitions/words","title":"Please list any incorrect words."},"choices":{"$ref":"#/definitions/choices","title":"Is this headline correct?"}}}`

strips out the titles in the resulting parsed schema. It works correctly if the "title" is places on the referenced definitions.

Is this expected/correct behaviour? If so, the validator should complain?

**Comment by JamesNK** [comment]
Hi

Any properties other than `$ref` are ignored. This behavior is part of the official specification.

http://json-schema.org/latest/json-schema-core.html#rfc.section.8

> An object schema with a "$ref" property MUST be interpreted as a "$ref" reference. The value of the "$ref" property MUST be a URI Reference. Resolved against the current URI base, it identifies the URI of a schema to use. All other properties in a "$ref" object MUST be ignored.
