### ISSUE TITLE
StackOverflowException in JSchemaReader.LoadAndSetSchema()

### ISSUE THREAD

**Issue by barsukovsky** [JamesNK/Newtonsoft.Json.Schema#11]
I have two files that reference to each other. They stored in local directory and I use relative references for this purpose.

First: obj_branch.schema.json

{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "id": "obj_branch.schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "see_also": {
      "extends": { "$ref" : "prop_see_also.schema.json" }
    }
  }
}

Second: prop_see_also.schema.json

{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "id": "prop_see_also.schema.json",
  "type": "array",
  "items": {
    "extends": { "$ref" : "obj_branch.schema.json" }
  }
}

StackOverflowException was thrown when I tried to parse first schema (obj_branch.schema.json) like this:

            const string DIRECTORY = @"E:\SchemaDir\";

            var schemaJson = File.ReadAllText(Path.Combine(DIRECTORY, "obj_branch.schema.json"));
            var schema = JSchema.Parse(schemaJson, new JSchemaReaderSettings
            {
                BaseUri = new Uri(DIRECTORY),
                Resolver = new JSchemaUrlResolver()
            });

**Comment by JamesNK** [comment]
Thanks for the repro. Fixed. Will be in the next release.

**Comment by JamesNK** [comment]
1.0.7 on NuGet has the fix.
