### ISSUE TITLE
MIT or Apache licenses

### ISSUE THREAD

**Issue by iSazonov** [JamesNK/Newtonsoft.Json.Schema#110]
I tried to use Newtonsoft.Json.Schema in [PowerShell Core](https://github.com/PowerShell/PowerShell) but there are [legal problems](https://github.com/PowerShell/PowerShell/pull/4896#issuecomment-335970211).

Can we get Newtonsoft.Json.Schema under MIT or Apache licenses?

**Comment by JamesNK** [comment]
Hi. Newtonsoft.Json.Schema is AGPL so I can support Newtonsoft as a business and allows me to spend more time working on other open source projects that are MIT, e.g. Json.NET. I appreciate that you want everything to be open but there is a limit of how much of my time I can give away for free.

What they suggested, releasing the powershell module outside of their project using AGPL, is something you could do.

**Comment by iSazonov** [comment]
How sad!
Thank you for the explanation and the great product!
