### ISSUE TITLE
StringEnumGenerationProvider does not change default to string value

### ISSUE THREAD

**Issue by ronaldbarendse** [JamesNK/Newtonsoft.Json.Schema#111]
When using the `StringEnumGenerationProvider` and setting the default value to an enum value, the numerical default value is used (instead of the string name).

Using the example code from the [documentation](https://www.newtonsoft.com/jsonschema/help/html/GenerateWithProvider.htm), the following schema is generated:

```C#
public class BuildingReport
{
    public DateTime Date { get; set; }
    [DefaultValue(BuildingZone.Residential)]
    public BuildingZone Zone { get; set; }
}
```

```JSON
{
    "type": "object",
    "properties": {
        "Date": {
            "type": "string"
        },
        "Zone": {
            "type": "string",
            "default": 0,
            "enum": [
                "Residential",
                "Commercial",
                "Industrial"
            ]
        }
    },
    "required": [ "Date", "Zone" ]
}
```

I would expect `"default": 0` to be `"default": "Redidential"` instead.

For now, using the string name as default value (using `[DefaultValue(nameof(BuildingZone.Residential))]`) creates a valid schema, but that could cause problems if the `DefaultValueAttribute` is used for other purposes.

**Comment by JamesNK** [comment]
Thanks for reporting it. It will be fixed in the next release https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/d857fbb9793de8e4c31ff414fd95fbc52ee09782
