### ISSUE TITLE
Is async custom validator supported

### ISSUE THREAD

**Issue by phoenixjun** [JamesNK/Newtonsoft.Json.Schema#113]
We are using the Json schema to validate the request and we would like to create a custom validator following that. https://www.newtonsoft.com/jsonschema/help/html/CustomJsonValidators.htm 

When we perform the validation, we will need to load data from external asynchronously. However, it seems like that the validator will return directly if we use async/await pattern in the code. Is that supported?

```

// validator
someobject.IsValid(jsonSchema, out validationErrors); // this will trigger the custom validator

// custom validator
public override async void Validate(JToken value, JsonValidatorContext context) {
    var data = await getdate();  // this will return and the isvalid function is always true regardless.
   // do something
}
```

**Comment by JamesNK** [comment]
Async validator is something that may happen in the future but it is a big change so won't come quickly.

I recommend using a helper method to call the async code from your validator - https://stackoverflow.com/a/25097498/11829
