### ISSUE TITLE
Generate Schema: A string array with EnumDataType attribute does not generate a schema with a list of valid enum values.

### ISSUE THREAD

**Issue by crustgi** [JamesNK/Newtonsoft.Json.Schema#116]
The schema should generated should look like:

{
    "type": "array",
    "items": {
        "type": "string",
        "enum": ["one", "two", "three"]
    }
}

but is instead

{
    "type": "array",
    "items": {
        "type": ["string", "null"]
    }
}

**Comment by JamesNK** [comment]
I looked at the docs for EnumDataTypeAttribute is only meant to be placed against a value when that value itself is an enum. Putting the attribute on a collection and expecting it to be applied to the children of the collection breaks what it is designed for.

**Comment by crustgi** [comment]
So that I understand this properly, you are against hijacking EnumDataTypeAttribute for creating a json schema but are fine with say EnumArrayDataTypeAttribute to achieve what I want?
