### ISSUE TITLE
Not validating seemingly valid URI's

### ISSUE THREAD

**Issue by arrkaye** [JamesNK/Newtonsoft.Json.Schema#117]
According to the JSON Schema spec, a URI can also be a relative reference.

So: "ZJKsiY+8" is apparently a valid URI (spec: https://tools.ietf.org/html/rfc3986#section-4.1).

Therefore, I believe the below schema and data should be valid. Yet JSON Schema says it isn't.

`{
  "definitions": {
    "url": {
      "title": "Delivery Location (URL)",
      "type": "string",
      "format": "uri"
    }
  },
  "type": "object",
  "properties": {
    "my_url": {
      "$ref": "#/definitions/url"
    }
  },
  "required": [
    "my_url"
  ]
}`

And the data: 

`{
	"my_url":"ZJKsiY+8"
}`

**Comment by JamesNK** [comment]
Are you sure it is valid? I tried out your schema and JSON at https://jsonschemalint.com/#/version/draft-06/markup/json and got a validation error: should match format "uri"
