### ISSUE TITLE
It does not like "id"?

### ISSUE THREAD

**Issue by lbcsy** [JamesNK/Newtonsoft.Json.Schema#119]
Following schema failed with message "Error when resolving schema reference '#/definitions/Element'. Path '', line 1, position 1."

> {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://hl7.org/fhir/json-schema/Element",
  "$ref": "#/definitions/Element",
  "description": "see http://hl7.org/fhir/json.html#schema for information about the FHIR Json Schemas",
  "definitions": {
       "Element": { }
      }
}

To fix it, change "id" to either "$id" or something not "id" such as "id1" etc.
Why it does not like "id"? is "id" a keyword?

**Comment by JamesNK** [comment]
It is because in draft4 `id` will create a new id container scope in JSON Schema. That id container scope is preventing the `$ref` path from being resolved.
