### ISSUE TITLE
set enum in JSchema is not possible from String Array

### ISSUE THREAD

**Issue by abaka-spn** [JamesNK/Newtonsoft.Json.Schema#123]
I'm trying to create a dynamic JSchema from the configuration file and I want to set the enum property.

Set action is not available, is it normal ?

How create a collection of valid enum values from string array or int array ?

**Comment by JamesNK** [comment]
Just add to the `enum` property collection.

```
JSchema s = new JSchema();
s.Enum.Add("option1");
s.Enum.Add("option2");
```

**Comment by abaka-spn** [comment]
It's obvious. Sorry
Thanks.
