### ISSUE TITLE
Incorrect validation using contains/enum

### ISSUE THREAD

**Issue by chrisport** [JamesNK/Newtonsoft.Json.Schema#124]
I ran the following sample on jsonschemavalidator.net and it tells me that the json has error, but it matches the schema.
**JSON Schema:**
```
{
  "properties": {
    "contexts": {
      "type": "array",
      "allOf": [
        {
          "contains": {
            "type": "object",
            "properties": {
              "name": {
                "enum": [
                  "A_name"
                ],
                "type": "string"
              }
            }
          }
        },
        {
          "contains": {
            "type": "object",
            "properties": {
              "name": {
                "enum": [
                  "B_name"
                ],
                "type": "string"
              }
            }
          }
        }
      ]
    }
  }
}
```

**Test JSON:**
```
{
  "contexts": [
    {
      "name": "A_name"
    },
    {
      "name": "B_name"
    }
  ]
}
```

**Result:**
```
Found 1 error(s)
Message:
   JSON does not match all schemas from 'allOf'. Invalid schema indexes: 1.
     Schema path:
        #/properties/contexts/allOf
```

**Comment by JamesNK** [comment]
Why do you think it would it be valid? The first schema in the allOf will only accept "A_name" and the second schema will only accept "B_name", so being mutually exclusive no value will ever pass both.

**Comment by chrisport** [comment]
Please note that the allOf applies on the array, not on the items and the "contains" means that the array must contain the specified item. So the array must contain a A_name, as well as a B_name.

**Comment by JamesNK** [comment]
I investigated, identified and fixed the bug. Thanks for the detailed reproduction.

Is the problem blocking you? I can make a new release now or wait if it isn't urgent.

**Comment by chrisport** [comment]
That was quick. It's not blocking me, I just wanted to report it, thanks!

**Comment by JamesNK** [comment]
Ok! I'll release it in the next few weeks and update jsonschemavalidator.net when I do
