### ISSUE TITLE
Support for extended DescriptionAttribute

### ISSUE THREAD

**Issue by EricKeij** [JamesNK/Newtonsoft.Json.Schema#125]
We put Description attributes on our properties the get the description in the generated schema. This all worked fine until we switched to a custom Description attribute (extending the System.ComponentModel.Description attribute) which sets the DescriptionValue from a resource file. Now the descriptions are ignored. Is it possible to support this scenario?

**Comment by JamesNK** [comment]
Thanks for reporting this, it is now supported - https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/e6185384818afa27a805d52156220fed01b6c2ba

It will be in the next release
