### ISSUE TITLE
Namespace conflict when using JsonSchema

### ISSUE THREAD

**Issue by maordavidov** [JamesNK/Newtonsoft.Json.Schema#126]
I'm referencing the Newtonsoft.Json.Schema 3.0.5 package and this also reference the Newtonsoft.Json 10.0.3 package.
When trying to use JsonSchema type I always receive the one from Newtonsoft.Json package which marks as Obsolete. 

Please change the namespace of the old \ new JsonSchema so those conflicts will be resolved using namespaces OR remove the obsolete JsonSchema type from Newtonsoft.Json package.

**Comment by JamesNK** [comment]
You should never use `JsonSchema`. It doesn't exist in Json.NET Schema and has been completely replaced with `JSchema`.

**Comment by Stan-Stani** [comment]
I'm still new to .NET but this sort of confusion has been ongoing for a while: https://stackoverflow.com/questions/35298231/newtonsoft-json-schema-jsonschema-is-obsolete

I just encountered this confusion.
