### ISSUE TITLE
JSchemaValidatingReader converts numeric values to booleans sucessfully

### ISSUE THREAD

**Issue by titanski** [JamesNK/Newtonsoft.Json.Schema#128]
Assigning a **numeric** value to a boolean property in JSON string will result in it being parsed and assigned the value "**true"** when using the JSchemaValidatingReader for validation while deserializeing the JSON string to an object.
 
For example, parsing the following JSON string  :
```
{
     "IsProcessed" : 5
}
```
With the following Json schema:
 
```
{
  "id": "http://site.somewhere/entry-schema#",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "Json Schema for DSP Data Catalog Data Set",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "IsProcessed"
  ],

  "properties": {
   "IsProcessed": { "type": "boolean" }
  }
}

```
Deserializing the JSON with the following logic :
```
 private static TObject Deserialize<TObject>(JsonReader jsonReader, JSchema schema)
        {
            using (var validatingReader = new JSchemaValidatingReader(jsonReader))
            {
                var validationErrors = new List<string>();

                validatingReader.Schema = schema;
                validatingReader.ValidationEventHandler += (o, error) => validationErrors.Add(error.Message);

                var serializer = new Newtonsoft.Json.JsonSerializer();

                // ReSharper disable once AccessToDisposedClosure
                var entity = serializer.Deserialize<TObject>(validatingReader);

                ThrowOnError(Properties.Resources.DeserializerError, validationErrors);
                return entity;
            }
        }
```
Result: 
Validation passes and the value "true" is assigned to the property after deserialization.

This behavior is consistent with the following documentation for booleans for **Jasascript** : 
https://www.w3schools.com/js/js_booleans.asp
The following sentence in particular: 
**"Everything With a "Value" is True"**

However, this behavior is inconsistent according to the **JSON** definition for boolenas:
https://www.w3schools.com/js/js_json_datatypes.asp
Which specifies that: 
**Only true/false are acceptable values for a booleans**

JSchemaValidatingReader should validate the JSON according to JSON definition of booleans and not the JavaScript one.

**Comment by JamesNK** [comment]
Yeah that's definitely a bug.

For now you can validate JSON by loading the string into a `JToken` and then calling `IsValid(JSchema)` on the token. I'll investigate how to fix this issue when using `JSchemaValidatingReader`.

**Comment by titanski** [comment]
Thanks!

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/a07ae0838bb52951b213b7bd3cf09fb26a474f81

Will be in the next release.
