### ISSUE TITLE
Something wrong with "OneOf"?

### ISSUE THREAD

**Issue by lbcsy** [JamesNK/Newtonsoft.Json.Schema#129]
Hi James,

Thanks for your work which allow me to add schema validation into my application.

So far it works perfectly to validate a normal Json object but seems failed to validate a Json object which contains objects that are defined as "OneOf" in the schema. In my case, I have a schema defines a type "Bundle", in a Bundle, it has an array "entry" which can have any one of defined other type as an array item, such as Patient and Practioner. I have attached the complete schema file for Bundle, and a sample Json of Bundle contains one Practioner and one Patient as the array of "entry", I tried with https://www.jsonschemavalidator.net/, the validation failed and reported failure against every possible object defined in the list of "OneOf". The Practioner and Patient objects have nothing wrong as they can pass the validation individually. The attachment "Sample-practioner.json.txt" and "Sample-patient.json.txt" are the extraction of the two json objects from the bundle json. 
 

[FHIR-Bundle-Schema.json.txt](https://github.com/JamesNK/Newtonsoft.Json.Schema/files/1756903/FHIR-Bundle-Schema.json.txt)
[Sample-Bundle-Patient.json.txt](https://github.com/JamesNK/Newtonsoft.Json.Schema/files/1756904/Sample-Bundle-Patient.json.txt)
[Sample-practioner.json.txt](https://github.com/JamesNK/Newtonsoft.Json.Schema/files/1756905/Sample-practioner.json.txt)
[Sample-Patient.json.txt](https://github.com/JamesNK/Newtonsoft.Json.Schema/files/1756906/Sample-Patient.json.txt)

**Comment by JamesNK** [comment]
To match `oneOf` you have to match exactly one of the schemas. You're matching more than one.
