### ISSUE TITLE
No way to discern $ref-sourced properties from inline ones

### ISSUE THREAD

**Issue by StenPetrov** [JamesNK/Newtonsoft.Json.Schema#13]
I poked around and it looks like the Properties are populated from a $ref when parsing the schema and that reference is then dismissed.

Is there any way to tell that these properties:

`"properties":  {
"billing_address": { "$ref": "#/definitions/address" },
"shipping_address": { "$ref": "#/definitions/address" }
}`

are of the same type after the schema is parsed?

**Comment by JamesNK** [comment]
They're the same object instance. A simple == or object.Equals will return true.
