### ISSUE TITLE
Schema validator, validates trailing comma in array.

### ISSUE THREAD

**Issue by zfields** [JamesNK/Newtonsoft.Json.Schema#133]
I was using http://jsonschemavalidator.net/ to test parse my JSON strings, and I noticed the validator will validate a trailing comma in an array.

The following string is successfully parsed by the validator:

```
[2,3,4,]
```

However, https://www.json.org depicts an array validation state machine (taken from [ECMA spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf)), that would not be capable of parsing trailing commas.

**Comment by JamesNK** [comment]
Hi

That is a quirk of how Json.NET reads JSON and the fix would be there. See this issue - https://github.com/JamesNK/Newtonsoft.Json/issues/646
