### ISSUE TITLE
Schema Resolution Bug

### ISSUE THREAD

**Issue by sprotty** [JamesNK/Newtonsoft.Json.Schema#137]
I've noticed a bug that's been introduced I think somewhere between 3.0.4/10.0.3 and the current build.
Basically the schema resolution path being constructed is wrong.

If you run the sample up it will throw an exception in XmlToJsonResolverAdapter as the BaseUri of the SchemaReference is being calculate wrongly.

Note : The sample JSON schema files are in the debug folder. 
[JsonResolutionIssue.zip](https://github.com/JamesNK/Newtonsoft.Json.Schema/files/1886222/JsonResolutionIssue.zip)

**Comment by sprotty** [comment]
I'm unclear how the resolution logic should be performed.

Give a schema in a file located at "http://server.com/myschemas/root.json"

  {
       "$id": "NewScope.json",
       "definitions": {
           "A": { }
           "B": { $ref="../Other.json#/definitions/C" }
       }
  }

I would expect the qualified path to A to be "http://server.com/myschemas/NewScope.json#/definitions/A"
As "NewScope.json" is resolved relative to the schemas actual url.
I would expect B to resolve to "http://server.com/Other.json#/definitions/C"

However my understanding of what your parser is doing.
It seems to resolve "A" as "NewScope.json#/definitions/A"
So when trying to resolve the reference "../Other.json#/definitions/C" relative to "NewScope.json#/definitions/A" it becomes "Other.json#/definitions/C" (can't see how that resolution is possible/valid) then makes it relative to the schema url giving "http://server.com/myschemas/Other.json#/definitions/C".

Can you clarify.

Thanks Simon

-----------------------------------------------------------------------------

Looking at the JSON Draft 6 spec for reference
https://tools.ietf.org/html/draft-wright-json-schema-01#section-9

  {
       "$id": "http://example.com/root.json",
       "definitions": {
           "A": { "$id": "#foo" },
           "B": {
               "$id": "other.json",
               "definitions": {
                   "X": { "$id": "#bar" },
                   "Y": { "$id": "t/inner.json" }
               }
           },
           "C": {
               "$id": "urn:uuid:ee564b8a-7a87-4125-8c96-e9f123d6766f"
           }
       }
   }

   The schemas at the following URI-encoded JSON Pointers [RFC6901]
   (relative to the root schema) have the following base URIs, and are
   identifiable by either URI in accordance with Section 5 above:

   # (document root)  http://example.com/root.json#
   #/definitions/A  http://example.com/root.json#foo
   #/definitions/B  http://example.com/other.json
   #/definitions/B/definitions/X  http://example.com/other.json#bar
   #/definitions/B/definitions/Y  http://example.com/t/inner.json
   #/definitions/C  urn:uuid:ee564b8a-7a87-4125-8c96-e9f123d6766f

**Comment by JamesNK** [comment]
The thing is your root schema ID is "LRBIV". There are no sub-directories beneath it so "../../.." in the schema $ref being resolved makes no sense and has no effect.

Maybe it should throw an error rather silently be ignored.

**Comment by sprotty** [comment]
OK, but in the Draft 6 schema spec example
 #/definitions/B  resolves to http://example.com/other.json
by that logic this should just resolve to "other.json", unless the root schema has some special logic that is applied?

**Comment by JamesNK** [comment]
"other.json" is relative. It replaces the current level of the root - "http://example.com/root.json" - which results in "http://example.com/other.json".

What would you expect "../../other.json" to resolve to in this circumstance? Since it makes no sense I would say an error.

**Comment by sprotty** [comment]
In that example you can't go back, and the reference is incalculable.
But given the qualified name for the root schema is "http://server.com/myschemas/root.json" without the id
Then when an id is added the name is calculated relative to the it, and so should become "http://server.com/myschemas/NewScope.json".

From 9.2.1 in the spec 
 _When an implementation encounters the <#/definitions/single> schema,
   it resolves the "$id" URI reference against the current base URI to
   form <http://example.net/root.json#item>._

**Comment by sprotty** [comment]
And to further muddy the water

   _**The root schema of a JSON Schema document SHOULD contain an "$id"
   keyword with a URI (containing a scheme)**.  This URI SHOULD either not
   have a fragment, or have one that is an empty string.  [[CREF2: How
   should an "$id" URI reference containing a fragement with other
   components be interpreted?  There are two cases: when the other
   components match the current base URI and when they change the base
   URI.  ]]_

...

_The effect of defining an "$id" that neither matches the above
   requirements nor is a valid JSON pointer is not defined._

The root schema shouldn't (not can't - although it sounds like its shouldn't be allowed) have a relative uri.
Are we in the realms of the "not defined"?

**Comment by JamesNK** [comment]
Basically. The way Json.NET Schema works is it will resolve the current $ref against parent $id scopes, in this case the root $id. That $id then resolves against the BaseUrl.
