### ISSUE TITLE
Error validating DateTime value specified in enum

### ISSUE THREAD

**Issue by mrahl** [JamesNK/Newtonsoft.Json.Schema#138]
Newtonsoft.Json.Schema version 2.0.8, .NET Framework 4.6.1

I'm using JsonSchema in tests to validate generated JSON and I'm using enum to match expected values. There seems to be a bug in how it compares DateTime values, generating an error even though the data is correct. This approach works well with other data types.

Here is a simple repro as a Console Application:

```
class Program
{
    static void Main(string[] args)
    {
        var date = new DateTime(2018, 3, 14, 15, 9, 26, DateTimeKind.Utc);

        var schema =
            @"{
                'properties': {
                    'Date': { 'enum': [" + JsonConvert.SerializeObject(date) + @"], 'required': true }
                }
            }";

        Console.WriteLine("JSON SCHEMA");
        Console.WriteLine(schema);
        Console.WriteLine();

        var json = JsonConvert.SerializeObject(new DateTimeContainer {Date = date});

        Console.WriteLine("JSON DATA");
        Console.WriteLine(json);
        Console.WriteLine();

        var jsonObject = JObject.Parse(json);
        var jsonSchema = JSchema.Parse(schema);

        var valid = jsonObject.IsValid(jsonSchema, out IList<string> messages);

        Console.WriteLine("SCHEMA VALIDATION RESULT");
        Console.WriteLine(valid ? "VALID" : "INVALID, errors: ");
        foreach (var message in messages)
        {
            Console.WriteLine(message);
        }
        Console.ReadLine();
    }
}

class DateTimeContainer
{
    public DateTime Date { get; set; }
}
```

Output:

> JSON SCHEMA
> {
>                 'properties': {
>                     'Date': { 'enum': ["2018-03-14T15:09:26Z"], 'required': true }
>                 }
>             }
> 
> JSON DATA
> {"Date":"2018-03-14T15:09:26Z"}
> 
> SCHEMA VALIDATION RESULT
> INVALID, errors:
> Value "2018-03-14T15:09:26Z" is not defined in enum. Path 'Date', line 1, position 30.

**Comment by mrahl** [comment]
2.0.8 is what I'm currently using in the tests. I also tried 3.0.10 in the console app and it has the same behavior.

**Comment by JamesNK** [comment]
Hi

I found your bug - the ISO date was being loaded as a date and not a string.

You can solve it by loading the JSchema using this helper method. Future versions (3.0.11+) will have the fix built in.

```
public static JSchema Parse(string json, JSchemaReaderSettings settings)
{
    using (JsonReader reader = new JsonTextReader(new StringReader(json)))
    {
        reader.DateParseHandling = DateParseHandling.None;
        JSchema s = JSchema.Load(reader, settings);

        // read to make sure there isn't additional content
        reader.Read();

        return s;
    }
}
```
