### ISSUE TITLE
Could not resolve schema reference of this type: 'schema.json/#address'

### ISSUE THREAD

**Issue by dmnreddy** [JamesNK/Newtonsoft.Json.Schema#14]
Hi,

I'm getting 'Could not resolve schema reference 'schema.json/#address'"' error when I tried to resolve the reference of the schema that is present in other file. Please look into this.

Here is the code to load the jsonschema:

  resolver.Add(new Uri("schema.json", UriKind.RelativeOrAbsolute),new FileStream("schema.json",FileMode.Open));
            JSchema sampleSchema = JSchema.Parse(@"{
                                                          'type': 'object',
                                                          'allOf': [
                                                            { '$ref': 'schema.json#address' }
                                                          ],                                                          
                                                        }", resolver);

Here is schema.json file that i'm referring to 
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  }
}

Please fix it.Thank you.

**Comment by JamesNK** [comment]
The address schema is nested inside the definitions property. Change your reference to:

{ '$ref': 'schema.json#/definitions/address' }

**Comment by dmnreddy** [comment]
Thank you very much for the solution. 

Could you let me know referring the following scenario is possible or not.
i.e. the referring to schema  that is outside the definition. 
{
"definitions": { },

"address": {
"type": "object",
"properties": {
"street_address": { "type": "string" },
"city": { "type": "string" },
"state": { "type": "string" }
},
"required": ["street_address", "city", "state"]
}

}

Thanks in advance.

**Comment by JamesNK** [comment]
That will work.

**Comment by dmnreddy** [comment]
Hi James,

I'm sorry,I experimented with that but it's giving me the exception (Error when resolving schema reference 'schema.json#/address'. Path 'allOf[0]'). Here is what I did. path i'm referring to is      '$ref': 'schema.json#/address' by using above mentioned code.

And the schema I used the one I mentioned above shown below.
{
  "definitions": {}
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }  
}

Code: 
 JSchemaPreloadedResolver resolver = new JSchemaPreloadedResolver();         
            resolver.Add(new Uri("schema.json", UriKind.RelativeOrAbsolute),new FileStream("schema.json",FileMode.Open));
            JSchema sampleSchema = JSchema.Parse(@"{
                                                          'type': 'object',
                                                          'allOf': [
                                                            { '$ref': 'schema.json#/address' }
                                                          ],                                                          
                                                        }", resolver);
Please resolve or let me know if i'm not properly using the library.

Thank you so much.

**Comment by JamesNK** [comment]
Your JSON is invalid. There is no comma after ``"definitions": {}``

**Comment by dmnreddy** [comment]
Thanks for clarification it's working.

**Comment by lbcsy** [comment]
Hi dmnreddy,
According to your code, it seems to me that I (as the developer) need to pre-aware where the external referred schema is and prepare them before doing the validation?

**Comment by tkurskiev** [comment]
Hi!

Regarding that problem with '$ref" not working - this nuget (Newtonsoft.Json.Schema) recognizes '$def' keyword, use it instead of 'definitions', example:

`{
'$defs':{
'address': {
'type': 'object',
'properties': {
'street_address': { 'type': 'string' },
'city': { 'type': 'string' },
'state': { 'type': 'string' }
},
'required': ['street_address', 'city', 'state']
},
'car':{'type':'string'}
},

'description': 'A person',
'type': 'object',
'additionalProperties':false,
'properties':
{
'name': {'type':'string'},
'hobbies': {
'type': 'array',
'items': {'type':'string'}
}
},
'$ref': '#/$defs/address'
}`

**Comment by HSweta** [comment]
Getting the error : 'Could not resolve schema reference 'address.json#/address'. Path 'properties.address',

address.json
{
  "definitions": {},
  "address": {
    "type" :  "object",
    "properties": {
      "street_address": {
        "type": "string"
      },
      "city": {
        "type": "string"
      },
      "state": {
        "type": "string"
      }
    }
  },
  "required": [
    "street_address",
    "city",
    "state"
  ]
}

schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "address": {
      "$ref":"address.json#/address"
    }
  }
}



While validation this schema I am getting error
Please Let me know what's wrong
