### ISSUE TITLE
How to define nullable int?

### ISSUE THREAD

**Issue by fizxmike** [JamesNK/Newtonsoft.Json.Schema#145]
I have a poperty of type Nullable\<Int32\>, which would have a type definition in JsonSchema like so:
```
"type": [
    "integer",
    "null"
]
```
But when defining new JSchema, the the Type parameter only accepts a single JSchemaType.

How would I define a nullable integer property with JSchema?

**Comment by JamesNK** [comment]
JSchemaType is a flags enum so you can combine values:

```
schema.Type = JSchemaType.Integer | JSchemaType.Null;
```
