### ISSUE TITLE
Need the way to mark a property as NOT REQUIRED.

### ISSUE THREAD

**Issue by fastwit** [JamesNK/Newtonsoft.Json.Schema#15]
That's what I'm expecting from generator:

        [TestFixture]
        public class PropertiesShouldNotBeRequiredTest
        {
            public class IssueModel
            {
                public int IssueId { get; set; }//default is 0 and it is ok
                public string Title { get; set; }
                public string Description { get; set; }
                public object OptionalProperty { get; set; }
                public int? NotUsedInt { get; set; }
            }

            [Test]
            public void Test()
            {
                var schemaGenerator = new JSchemaGenerator();
                var jsonSchema = schemaGenerator.Generate(typeof(IssueModel));

                Assert.AreEqual(0, jsonSchema.Required.Count);
            }
        }

**Comment by JamesNK** [comment]
The next release will have a DefaultRequired property that will specify whether properties are required. I'll put a comment here when it is available.
