### ISSUE TITLE
JSchema.Valid incorrect ToString

### ISSUE THREAD

**Issue by wasabii** [JamesNK/Newtonsoft.Json.Schema#153]
I think, but am having trouble finding in the spec, that a JSchema with `.Valid == true` should actually render as a JSON object `{}`. Where as `.valid == false` should render some other way.

Newtonsoft.JSchema is rendering it as the JSON token `true` or the JSON token `false`.

Am I wrong here?

**Comment by JamesNK** [comment]
They're boolean schemas - http://json-schema.org/latest/json-schema-core.html#rfc.section.4.3.1
