### ISSUE TITLE
Error when resolving schema reference for Azure RM template parameters

### ISSUE THREAD

**Issue by RobDesideri** [JamesNK/Newtonsoft.Json.Schema#159]
Trying to validate an Arm template parameters file ([schema](https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json)), the library  throw the error `Error when resolving schema reference 'https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#/definitions/parameterValueTypes'. Path 'definitions.parameter.properties.value', line 33, position 18.'`

This error appears both in my own implementation and also doing an online test on https://www.jsonschemavalidator.net/.  
I tried to clone the project and find the cause of this error without success. The only thing I discovered is the error is fired on the `ResolveDeferedSchema` method of the `JSchemaReader` class.

Note: the ARM schemas are on github at https://github.com/Azure/azure-resource-manager-schemas.

**Comment by JamesNK** [comment]
I tested it out and it appears to work. I'm guessing there was a mistake in their schema that they have fixed.
