### ISSUE TITLE
Unable to validate Invalid Email ID (some invalid patterns) with  "format:email"

### ISSUE THREAD

**Issue by dmnreddy** [JamesNK/Newtonsoft.Json.Schema#16]
Hi,

I'm trying to validate some email address, but its not validating some invalid patterns.

Here is my Schema and the JSON

{
  "description" : "Example Contact Information Array JSON Schema",
  "type" : "array",
  "items" : {
    "title" : "A Contact Information object",
    "type" : "object",
    "properties" : {
      "name" : {
        "type" : "string",
        "enum" : ["home", "work", "other"]
      },      
      "email" : {
        "type" : "string",
        "optional" : true,
        "format" : "email"
      }
    },
    "minItems" : 1,
    "maxItems" : 5
  }
}

JSON:

[{
	"name": "home",	
	"email": "xyz@acd.eu"
},
{
	"name": "work",	
	"email": "{xyz@abc.gr"
}]

The email provided above "{xyz@abc.gr" is invalid, but when I tried with http://www.jsonschemavalidator.net/ its not showing any errors. At the same time if I write like "email": "{xyz@abc.gr}" added another closing brace then it is able to validate saying invalid email.

Please check this.

**Comment by JamesNK** [comment]
Hi

"{xyz@abc.gr" is a valid email.

http://isemail.info/%7Bxyz%40abc.gr
