### ISSUE TITLE
Does free license has performance limitations?

### ISSUE THREAD

**Issue by MNF** [JamesNK/Newtonsoft.Json.Schema#160]
The page 
https://www.newtonsoft.com/jsonschema shows that Newtonsoft.Json.Schema has license

> AGPL 3.0 | Free with limitations (1000 validations per hour)

But on 
https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/master/LICENSE.md no limitations mentoned

> This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, see http://www.gnu.org/licenses/agpl-3.0.html.

Which one is correct? Please update them to be consistent.

**Comment by JamesNK** [comment]
There is a 1000 validation/h restriction with AGPL.

**Comment by suneetnangia** [comment]
Additional query @JamesNK, if we consider using schema validator for an OSS base redistributable container, which license should be acquired? Do we need single dev licence for the dev who made the changes to include schema validator in OSS? or there's more to it? Thanks
