### ISSUE TITLE
Generating json schema from json string

### ISSUE THREAD

**Issue by yvz5** [JamesNK/Newtonsoft.Json.Schema#164]
is it possible to generate a json schema from a string without having the c# types ? I have a system where I cant have c# types for json files. I can only read them at runtime.

```csharp
var json = "{ \"test\": 123 }";
dynamic jObj = JObject.Parse(json);
JSchemaGenerator generator = new JSchemaGenerator();
JSchema schema = generator.Generate(jObj.GetType());
Console.WriteLine(schema.ToString());
```

this prints  `{}`

**Comment by JamesNK** [comment]
No that's not possible. `JSchemaGenerator` only works with static .NET types.

https://www.jsonschema.net/ is an online tool for infering a schema from JSON.

**Comment by xyz-mtl** [comment]
@JamesNK : Is it possible to have an enhancement for this feature ? Or an alternative ?

**Comment by yvz5** [comment]
I have solved this using nodejs and calling it from c# to automate the process
