### ISSUE TITLE
StringEnumGenerationProvider fails on Enum members with same value

### ISSUE THREAD

**Issue by syncro-bpierpont** [JamesNK/Newtonsoft.Json.Schema#166]
If an enum contains members with the same value StringEnumGenerationProvider recognizes only one of the members.

For example, for the following enum "A" and "B" are considered valid, "ON" and "OFF" are not:
```
public enum SwitchPosition
    {
        UNKNOWN = 0,
        ON = 1,
        OFF = 2,
        A = 1,
        B = 2
    }
```

**Comment by JamesNK** [comment]
Thanks for reporting this. Fixed.
