### ISSUE TITLE
Error de-serializing Json Schema because the Type parameter of property type is sometimes an array and sometimes string.

### ISSUE THREAD

**Issue by vinaysharma77** [JamesNK/Newtonsoft.Json.Schema#169]
I'm running into an issue where I'm generating a JSON schema for a model in which I have properties collection for all the fields of my model. For the properties that are marked as not required (nullable), the "type" parameter for those is an array with two values for that property: the respective datatype of the field (string, integer, object etc.) and a "null":

                  "cif": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "name": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },

The reason why I'm getting an array in the type parameter for these properties is because I've assigned two JSchemaType Enum values to the Type when creating these properties

new JSchema() { Type = JSchemaType.Integer |  JSchemaType.Null})

But there are some properties which are marked as required (non-nullable). And for those properties, when creating a JSON Schema the Type is either assigned as JSchemaType.Integer or JSchemaType.String. This translates to the following JSON for those properties:

      "_entityId": {
        "type": "string"
      },
      "_typeId": {
        "type": "integer"
      },

Finally when I get the schema, my property collection contains all these properties, some with "type" as an array and some having "type" as a string.

This is causing issues when trying to consume this JSON schema and de-serializing it as the Type property I've defined in my POCO can either be a string or an array, not both.

I explored an option of trying to creating an array with one single item when generating properties for the fields marked as "required", but the way JSON Schema gets built, it doesn't take anything else other than the JSchemaType Enum as a value to the Type field.

I need to have a uniform datatype of the Type of the properties in the JSON Schema but still be allowed to have more than one values for the Type for some properties. How do I accomplish that?

-Vinay

**Comment by JamesNK** [comment]
This is expected behavior. The JSON spec says that the type value can be a string or an array. You need to be able to handle that. `JSchema.Parse` will handle loading JSON into a schema object model you can query.
