### ISSUE TITLE
Readonly support

### ISSUE THREAD

**Issue by andresmoschini** [JamesNK/Newtonsoft.Json.Schema#17]
It seems that `readonly` property is not supported, see http://json-schema.org/latest/json-schema-hypermedia.html#rfc.section.4.4

**Comment by JamesNK** [comment]
That's from the hyper-schema spec. Also readonly it doesn't effect validation. It is a runtime behavior, not a data behavior.

**Comment by andresmoschini** [comment]
Thanks @JamesNK for your quick response, and you are right. 

But I understand that the follow schema is valid

```json
"id":   {  
  "type": "integer",
  "readonly": true}
}
```

So hyper-schema _expands_ JSON schema. Is it possible to generate `readonly` property on generated schemas? what should be the _right_ or elegant way? implementing `JSchemaGenerationProvider`?


BTW, is it possible to implement an _attribute_ that implements `JSchemaGenerationProvider` or it should always be used in the follow way:

```
[JSchemaGenerationProvider(typeof(MyCustomSchemaGenerationProvider))]
string Property { get; set; }
```

Thanks!

**Comment by JamesNK** [comment]
Yes you could write a schema provider to add the property.
