### ISSUE TITLE
Wrong value passed to propertyName evaluation

### ISSUE THREAD

**Issue by Jubke** [JamesNK/Newtonsoft.Json.Schema#170]
There seems to be an error related to the `propertyNames` validation, where instead of the property name (`"validName"`) the name plus a null value (`"validName":null`) is evaluated against the `enum` . It only seem to happen when the object schema is used in combination with the `oneOf`. 

Or something is wrong with my schema, then I appreciate any hints.

Schema:
```JSON
{
  "type": "array",
  "items": {
    "oneOf": [
      {
        "type": "object",
        "propertyNames": {
          "type": "string",
          "enum": [
            "validName"
          ]
        },
        "additionalProperties": true
      },
      {
        "type": "string",
        "enum": [
          "validName"
        ]
      }
    ]
  }
}
```

JSON:
```JSON
[
  {
    "validName": {
      "a": 1
    }
  },
  "validName"
]
```

![image](https://user-images.githubusercontent.com/7038894/52534827-a58db900-2d46-11e9-9687-c50ec4dae0df.png)

**Comment by JamesNK** [comment]
Thanks for reporting this. Fixed!
