### ISSUE TITLE
Authenticode signature for Newtonsoft.Json.Schema

### ISSUE THREAD

**Issue by aaron-meyers** [JamesNK/Newtonsoft.Json.Schema#171]
I see that the most recent release of Newtonsoft.Json (12.0.1) has added Authenticode signature to the assembly. This is great as it means we don't need to manually sign it anymore with Microsoft 3rd party signature for shipping in our application (Microsoft Power BI Desktop).

Will you consider adding Authenticode signature to Newtonsoft.Json.Schema as well? We use both assemblies in Microsoft Power BI Desktop so it would be very helpful to have both of them signed (basically, reduces the time it takes for us to pick up the latest versions of these assemblies).

**Comment by JamesNK** [comment]
I cannot use the same key and infrastructure to sign because it belongs to the .NET Foundation and Newtonsoft.Json.Schema isn't in the .NET Foundation.

**Comment by aaron-meyers** [comment]
No worries, I just found out that we're still required to sign all of our third-party assemblies with the Microsoft 3rd party signature even if they have a separate signature. Thanks for taking a look.
