### ISSUE TITLE
Access definitions on ref property 

### ISSUE THREAD

**Issue by FransvVanEk** [JamesNK/Newtonsoft.Json.Schema#172]
I want to have access to the definitions in the schema in order to get the naming of the definition. I am using newtonsoft.json v11.01

I am building a c# converter for jsonschema to make a syntaxtree and compile it in order to get a typed version of the object at runtime.
```
{
  "$id": "https://example.com/arrays.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "xml remarks",
  "type": "object",
  "properties": {
    "fruits": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "fruit",
        "required": ["naam"],
        "properties": {
        "naam": {
          "type": "string",
          "description": "The name of the fruit."
        }
        }
      }
    },
    "vegetables": {
      "type": "array",
      "items": { "$ref": "#/definitions/veggie" }
    }
  },
  "definitions": {
    "veggie": {
      "type": "object",
      "required": [ "veggieName", "veggieLike" ],
      "properties": {
        "veggieName": {
          "type": "string",
          "description": "The name of the vegetable."
        },
        "veggieLike": {
          "type": "boolean",
          "description": "Do I like this vegetable?"
        }
      }
    }
  }
}
```
in the schema a reference is created with the name veggie. This is used in the property vegetable with a reference.

Json schema contains a definition on the root object but is doesn't have a reference to it on the property element. On the property element there is nothing identifiable to point to the right definition.

**Comment by ggirard07** [comment]
@FransvVanEk have you ever heard about [stackoverflow](https://stackoverflow.com)??

**Comment by FransvVanEk** [comment]
@ggirard07 	yes i have heard from it. I already had posted it there. Can i find your answer there? or is your comment not useful in anyway?

**Comment by ggirard07** [comment]
@FransvVanEk sorry for being rude. Most people start issues in GitHub now to ask questions whereas StackOverflow is the preferred platform for this. GitHub issues should be used to report bugs/improper behaviors/feature requests. 
The project documentation even state where to go to seek help https://www.newtonsoft.com/jsonschema#help, and I don't see GitHub issues listed in here.

If you already have tried StackOverflow, you could have at least linked it in you initial post, same on your StackOverflow post, for cross reference purpose.

**Comment by FransvVanEk** [comment]
@ggirard07 thank you for your response. I did read the documentation of github where to seek help. I even downloaded the source code in order to see if i was missing something. From the answers on Stackoverflow  i came to the conclusion that this is functionality is not properly implemented.  Although it doesn't fail, i consider it a bug not to have a proper reference to the definitions when they are referenced.

**Comment by JamesNK** [comment]
When `JSchema` loads the JSON text it will automatically denormalize schema references. For example, `schema.Properties["vegetables"].Items[0]` will be a reference to the schema in definitions with the name "veggie". If there are any other references to the same location they will share the same schema instance.

The original ref path - `{ "$ref": "#/definitions/veggie" }` - is not kept. I think what you want to do is not a supported scenario. If you want to capture that information then you will need to parse the JSON some other way.

**Comment by JamesNK** [comment]
If you want to identify a schema, adding a `$id` property is probably a better solution.

https://tools.ietf.org/html/draft-wright-json-schema-01#section-9.2

**Comment by FransvVanEk** [comment]
Ok, i managed to get it working with the Id although i would liked to have the path to the the original path kept so i could get more details from there without parsing the json once more.. 

thanks for the pointers
