### ISSUE TITLE
Error after upgrade of Json.net to 12

### ISSUE THREAD

**Issue by zpertee** [JamesNK/Newtonsoft.Json.Schema#174]
I'm getting an error after upgrading Json.net to 12, when calling License.RegisterLicense("");

Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by JamesNK** [comment]
Are you running on .NET Framework? You probably need to add a binding redirect to your web.config.

https://stackoverflow.com/questions/43365736/assembly-binding-redirect-how-and-why

**Comment by zpertee** [comment]
So, my setup is a bit overly complex.  I'm using Azure Functions with Visual Studio 2017 tooling (what Microsoft calls pre-compiled functions).  My Azure Function itself is .net 4.7.1, with a collection of custom .net standard class libraries (added as nuget packages) to do the bulk of the work.  I'm following these instructions: https://www.thewissen.io/azure-functions-binding-redirects/ to do the binding redirect, which worked perfectly for version 11.    

My issue is that when I've gone through and updated everything to version 12 it broke.  Unfortunately, my knowledge of binding redirects is a little weak, especially when going from the full .net framework version to .net standard nuget packages.  I think in the short term the best solution is to just stay on json.net version 11.  However, long term this poses some concern as we like to stay up to date for security, performance, and bugs.

**Comment by JamesNK** [comment]
Azure Functions doesn't like multiple versions of an assembly. I'd recommend sticking with Newtonsoft.Json version 11.

**Comment by zpertee** [comment]
FYI, my complexities here were completely resolved once Json.NET Schema version 3.0.11 was released and upgraded in my project.
