### ISSUE TITLE
ItemsPositionValidation needs to be set manually

### ISSUE THREAD

**Issue by fbarnard** [JamesNK/Newtonsoft.Json.Schema#18]
Hi

I am creating a schema manually. 

    var schema = new JSchema
    {
        Type = JSchemaType.Boolean
    };
    
    schema.ExtensionData.Add("name","name");
    
    schema.Properties.Add(new KeyValuePair<string, JSchema>("field1",new JSchema
    {
        Type = JSchemaType.Array,
       
    }));
    
    schema.Properties["field1"].Items.Add(
        new JSchema
        {
            Type = JSchemaType.String
        });
    
    schema.Properties["field1"].Items.Add(
       new JSchema
       {
           Type = JSchemaType.Boolean
       });
    
    schema.Properties["field1"].ItemsPositionValidation = true;

When i dont set ItemsPositionValidation =true and i tostring the schema it only returns one item.

Now i sort of get the idea that creating a schema manually is not really the way this was intendant i should rather load from json so that all internals can kick in but i thought i just mention it.

thanks

**Comment by JamesNK** [comment]
That is intended behavior. It is valid to only have a single item and have position validation, which is why ItemsPositionValidation exists. And I'd rather it need to be consistently set rather than automatically turn on in certain circumstances.
