### ISSUE TITLE
Parsing schema with "type": "file" results in exception

### ISSUE THREAD

**Issue by dalligieri** [JamesNK/Newtonsoft.Json.Schema#180]
When parsing schema with "type":"file" exception was thrown Newtonsoft.Json.Schema.JSchemaReaderException : Invalid JSON schema type: file.
Code is next
```
var schema = "{  \"type\": \"file\" }";
var result = JSchema.Parse(schema);
```
According to documentation, JSON Schema by itself did not define such type, but some vendors (e.g. Microsoft) uses such type in Swagger schemas and also I think there must be the way to extend pre-defined schema types list. 
Is there any workaround to parse custom types?

**Comment by JamesNK** [comment]
No there isn't. That isn't a valid schema type. Type must be one or more of these: https://json-schema.org/understanding-json-schema/reference/type.html
