### ISSUE TITLE
JSchemaConverter to write different version?

### ISSUE THREAD

**Issue by tutap** [JamesNK/Newtonsoft.Json.Schema#189]
Hello,

Is there any way I can make the converter to write different version? currently I have to apply my custom converter to every property because JSchema is already tagged with JSchemaConverter hence it won't use my custom converter

Thanks,

**Comment by JamesNK** [comment]
You could implement a contract resolver in Newtonsoft.Json and in it override the converter for JSchema: https://stackoverflow.com/a/45644338/11829

In your own converter you would call JSchema.WriteTo, and in the settings pass the schema version you want to write.

**Comment by tutap** [comment]
nice solution! thank you for your time and sorry I couldn't search for that.
