### ISSUE TITLE
"uniqueItems" property is not written in JSchemaWriter.cs

### ISSUE THREAD

**Issue by JakobMollas** [JamesNK/Newtonsoft.Json.Schema#19]
The "uniqueItems" property is not written when a schema is serialized.

See method WriteSchemaInternal(...) in https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/master/Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs

It should probably be located somewhere close to serialization of for example "AllowAdditionalItems", row 211.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/c33d9c0852f019b341d4a10dfbc0dfc0c6039706

Is this something you just noticed or is this bug blocking you?

**Comment by JakobMollas** [comment]
Thanks, that was quick!
No, it is not a blocker and something I found yesterday.
I use text serialization (basically schema.ToString()) to show resolved and "prettyfied" JSON Schema output in a small test application. So more of a nice to have at this point.
