### ISSUE TITLE
WF application exception HRESULT - Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0'

### ISSUE THREAD

**Issue by paulasavin** [JamesNK/Newtonsoft.Json.Schema#193]
I am having problems using Newtonsoft.Json.Schema in my Windows forms application. I am using **Json.NET v12.0.1** and **Json.NET.Schema v3.0.10**.

When I am running my application from standard bin output folder, it works properly. But my project needs to be portable, so I must be able to take the final .exe (_together with the dependent dlls_) and ran it wherever I need. When I am trying to execute it from another location, this exception occurs:

"Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". 

I tried also changing versions, including the portable one, and problem is still present. If I change the Netwonsoft.Json to version 11.0, the exception raises with being unable to load version 12.0.

**Comment by JamesNK** [comment]
You need to add a binding redirect - https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions
