### ISSUE TITLE
Mechanism to extend/add some annotation keywords

### ISSUE THREAD

**Issue by darl2ng** [JamesNK/Newtonsoft.Json.Schema#194]
Hi all,

For our application we need some new annotation keywords as described in this section :

http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.5

We avoid cheating with format, contentEncoding, contentMediaType (which we don't use yet), so we have investigated the code but could not find a nice solution to do this.

We do implement our own ConstractResolver and GenerationProvider, and customize the generation with SchemaReferenceHandling and such, so it does not make sense for us to rewrite all the generation logic with a new GenerationProvider (even if we did that, it would be a nightmare to maintain the code).

We would like to be able to:

- extend the JSchema class with some annotation keywords (beside format) and passing the derived instance through the generation process, and then with a custom GenerationProvider to provide the required information
- extend the JSchemaWriter to support these keywords

Is it something planned for the next version (roadmap) or there's some workaround that we was not aware of ?

Thank you in advance.

**Comment by JamesNK** [comment]
I think you can use JsonValidator for this - https://www.newtonsoft.com/jsonschema/help/html/CustomJsonValidator.htm

The example is using a custom format value, but you could look for custom properties using [ExtensionData](https://www.newtonsoft.com/jsonschema/help/html/P_Newtonsoft_Json_Schema_JSchema_ExtensionData.htm).

**Comment by darl2ng** [comment]
Thank you, ExtensionData works for us.

I thought it was for external schema and internal references (definitions) but not only we can use it for validation as you suggested, the default writer just print its content out without any customization.
