### ISSUE TITLE
Add GeoJson support.

### ISSUE THREAD

**Issue by payoff** [JamesNK/Newtonsoft.Json.Schema#2]
Examples: 
https://github.com/fge/sample-json-schemas/tree/master/geojson

**Comment by JamesNK** [comment]
Hi

The problem your having is caused by the schema references to the sub-schemas returning 404. You can get around this by saving the geojson files to disk and preloading the sub-schemas.

    public static JSchema OpenSchemaFile(string name, JSchemaResolver resolver)
    {
        string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;

        string path = Path.Combine(baseDirectory, name);

        using (JsonReader reader = new JsonTextReader(new StreamReader(path)))
        {
            JSchema schema = JSchema.Read(reader, resolver);
            return schema;
        }
    }

    [Test]
    public void GeoJson()
    {
        JSchemaPreloadedResolver resolver = new JSchemaPreloadedResolver();

        resolver.Add(OpenSchemaFile(@"resources\schemas\geojson\crs.json", resolver), new Uri("http://json-schema.org/geojson/crs.json#"));
        resolver.Add(OpenSchemaFile(@"resources\schemas\geojson\bbox.json", resolver), new Uri("http://json-schema.org/geojson/bbox.json#"));
        resolver.Add(OpenSchemaFile(@"resources\schemas\geojson\geometry.json", resolver), new Uri("http://json-schema.org/geojson/geometry.json#"));

        JSchema schema = OpenSchemaFile(@"resources\schemas\geojson\geojson.json", resolver);

        JObject o = JObject.Parse(@"{
          ""type"": ""Feature"",
          ""geometry"": {
            ""type"": ""Point"",
            ""coordinates"": [125.6, 10.1]
          },
          ""properties"": {
            ""name"": ""Dinagat Islands""
          }
        }");

        bool isValid = o.IsValid(schema);

        Assert.IsTrue(isValid);
    }
