### ISSUE TITLE
JSchema.Parse Seemingly Malforming Schema

### ISSUE THREAD

**Issue by arrkaye** [JamesNK/Newtonsoft.Json.Schema#200]
Hi,

We are using JSchema version 3.0.0, and are seeing some odd behaviour when parsing the below schema. Calling JSchema.Parse seems to resolve the refs in a strange way by referencing another part of the same object.

The specific part causing the issue is the `upper_limit` made to reference the `lower_limit` from the same `properties` and not the original reference provided in the source?

E.g.  `"upper_limit": { "$ref": "#/oneOf/0/properties/range/properties/lower_limit"`

Original:

`{ "type": "object", "definitions": { "cat": { "type": "string", "enum": [ "Value Provided" ] }, "cat_specific": { "title": "Multiple Choice", "type": "string", "enum": [ "Range" ] }, "number": { "type": "number" }, "range": { "type": "object", "title": "Range", "properties": { "lower_limit": { "$ref": "#/definitions/number", "title": "Lower Limit" }, "upper_limit": { "$ref": "#/definitions/number", "title": "Upper Limit" } }, "required": [ "lower_limit", "upper_limit" ] } }, "properties": { "cat": { "$ref": "#/definitions/cat" } }, "required": [ "cat" ], "dependencies": { "cat": { "oneOf": [ { "properties": { "cat": { "enum": [ "Value Provided" ] }, "cat_specific": { "$ref": "#/definitions/cat_specific" } }, "required": [ "cat_specific" ], "dependencies": { "cat_specific": { "oneOf": [ { "properties": { "cat_specific": { "enum": [ "Range" ] }, "range": { "$ref": "#/definitions/range" } } } ] } } } ] } } }`

Parsed:

`{ "definitions": { "cat": { "type": "string", "enum": [ "Value Provided" ] }, "cat_specific": { "title": "Multiple Choice", "type": "string", "enum": [ "Range" ] }, "number": { "type": "number" }, "range": { "title": "Range", "type": "object", "properties": { "lower_limit": { "$ref": "#/definitions/number" }, "upper_limit": { "$ref": "#/definitions/number" } }, "required": [ "lower_limit", "upper_limit" ] } }, "type": "object", "properties": { "cat": { "$ref": "#/definitions/cat" } }, "required": [ "cat" ], "dependencies": { "cat": { "oneOf": [ { "properties": { "cat": { "enum": [ "Value Provided" ] }, "cat_specific": { "title": "Multiple Choice", "type": "string", "enum": [ "Range" ] } }, "required": [ "cat_specific" ], "dependencies": { "cat_specific": { "oneOf": [ { "properties": { "cat_specific": { "enum": [ "Range" ] }, "range": { "title": "Range", "type": "object", "properties": { "lower_limit": { "type": "number" }, "upper_limit": { "$ref": "#/oneOf/0/properties/range/properties/lower_limit" } }, "required": [ "lower_limit", "upper_limit" ] } } } ] } } } ] } } } `

**Comment by alexdawes** [comment]
This issue is produced by the following cut-down schema:

```
{
  "type": "object",
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "bar": {
          "$ref": "#/definitions/bar"
        },
        "baz": {
          "$ref": "#/definitions/bar"
        }
      }
    },
    "bar": {
      "type": "string" 
    }
  },
  "dependencies": {
    "foo": {
      "oneOf": [
        {
          "properties": {
            "foo": {
              "$ref": "#/definitions/foo" 
            } 
          } 
        }
      ] 
    } 
  } 
}
```

As best we can tell, the issue is caused by the dependencies serialization, where use of shared $refs in the schema are incorrectly handled and result in new $refs being added that point back into the dependencies

**Comment by JamesNK** [comment]
Thanks for the good reproduction of your issue. There is a bug in how dependencies are written.

JSON after fix:
```json
{
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "bar": {
          "$ref": "#/definitions/bar"
        },
        "baz": {
          "$ref": "#/definitions/bar"
        }
      }
    },
    "bar": {
      "type": "string"
    }
  },
  "type": "object",
  "dependencies": {
    "foo": {
      "oneOf": [
        {
          "properties": {
            "foo": {
              "$ref": "#/definitions/foo"
            }
          }
        }
      ]
    }
  }
}
```
