### ISSUE TITLE
jsonschemavalidator: wrong type for maxProperties

### ISSUE THREAD

**Issue by nick4fake** [JamesNK/Newtonsoft.Json.Schema#201]
![image](https://user-images.githubusercontent.com/1065993/70866891-caab1380-1f77-11ea-8271-5a118fe21d69.png)

**Comment by JamesNK** [comment]
How do you get that error?

![image](https://user-images.githubusercontent.com/303201/71328136-0432de80-2577-11ea-8344-bc79cb002e95.png)

What is your schema? What is your data?
