### ISSUE TITLE
schema validate integer or number range

### ISSUE THREAD

**Issue by jerchap** [JamesNK/Newtonsoft.Json.Schema#204]
Specifying a range for an integer or number does not seem to work.  Range appears to be supported for integer and numeric types from a json schema perspective.

{
   'type': 'object',
    'additionalProperties': false,
    'properties': 
    {
       ' MyValue': {'type': 'integer', minimum:0, maximum:1}
    }
}

**Comment by JamesNK** [comment]
It works for me when I test using https://www.jsonschemavalidator.net/:

![image](https://user-images.githubusercontent.com/303201/72384174-bf6b2380-3781-11ea-8f18-591074c6e7f6.png)

**Comment by jerchap** [comment]
OH man,  you are right.  Bad mistake,  I was doing this in a unit test, and forgot to wrap in an assert!
