### ISSUE TITLE
Bug on Json and Schema Validation 

### ISSUE THREAD

**Issue by RoniTabuzo-EY** [JamesNK/Newtonsoft.Json.Schema#206]
Hi, 

I know this might be an unlikely case but it can happen when the two parameters have been switched (schema, json).
When i tried to switch the schema and json content, it still shows me valid even though i've already removed one element from the json.

[
<img width="1663" alt="Screenshot 2020-01-28 at 2 22 32 PM" src="https://user-images.githubusercontent.com/51104930/73240383-c8281480-41d9-11ea-967a-5f26401e7b3c.png">
](url)

**Comment by JamesNK** [comment]
It passes because the schema no longer contains any validation.
