### ISSUE TITLE
Flag enum

### ISSUE THREAD

**Issue by samuelpsfung** [JamesNK/Newtonsoft.Json.Schema#209]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags

`JSchemaGenerator.Generate(Type)` the enum will be int. I think the following schema is more appropriate:

```
{
  type: "array",
  items: {
      type: "string",
      enum: ["Monday", "Tuesday", ...]
  }
}
```

**Comment by JamesNK** [comment]
You can use StringEnumGenerationProvider with JSchemaGenerator to do this.

Sample here: https://www.newtonsoft.com/jsonschema/help/html/GeneratingSchemas.htm

**Comment by samuelpsfung** [comment]
Hi James,

Thanks for your advice, but that doesn't solve my problem.

The property type should be array of strings, not single string. It is an array because "combination of choice" is possible by "bitwise or" on the flag enum.
