### ISSUE TITLE
Possible to generate schema with definitions and $refs?

### ISSUE THREAD

**Issue by bentayloruk** [JamesNK/Newtonsoft.Json.Schema#21]
Is is possible to generate schema with `definitions` and `$refs`?  I was hoping I could generate a set of types, including the root type, and a collection of referenced types.

**Comment by kobynet** [comment]
+1

**Comment by JamesNK** [comment]
If a type is type is referenced multiple times there will only be one schema and multiple references to it.

**Comment by bentayloruk** [comment]
Thanks for the response @JamesNK.  I think this will do what I want.  However, I need to do some work an check.  Apologies, I had assumed a `definitions` property was required when `$ref`-ing, thus highlighting my need to learn more about JSON schema!
