### ISSUE TITLE
Support for "examples" keyword?

### ISSUE THREAD

**Issue by Fujakless** [JamesNK/Newtonsoft.Json.Schema#210]
Hello,
is there any plan of adding support for manipulation with the "examples" annotation?
Right now, I can read/write examples to the JSchema through ExtensionData, but it would be easier to just have an Examples property.

**Comment by JamesNK** [comment]
No plan at the moment. ExtensionData provides a generalized way of adding extra data like this, and the `examples` property isn't core to the runtime validation of schemas.

**Comment by palenshus** [comment]
@Fujakless, did you figure out a way do do this nicely with a workaround? We're looking to encode examples into our schema as well and it'd be great to have something to start with, thanks!
