### ISSUE TITLE
AGPL-3.0-only or AGPL-3.0-or-later?

### ISSUE THREAD

**Issue by capfei** [JamesNK/Newtonsoft.Json.Schema#218]
I'm trying to get the SPDX identifier for this license. The license states, "either version 3 of the License, see...", which is AGPL-3.0-or-later but leaves out, "or (at your option) any later version."

3.0-only just states "version 3."

Should it be AGPL-3.0-only or AGPL-3.0-or-later?

**Comment by JamesNK** [comment]
It should be AGPL-3.0-only

**Comment by capfei** [comment]
Thank you!
