### ISSUE TITLE
Cannot "$ref" JSON Schema on a TLSv1.3-only server

### ISSUE THREAD

**Issue by jakubklimek** [JamesNK/Newtonsoft.Json.Schema#225]
When a referenced schema is on a TLSv1.3-only server, the dereference fails. When TLSv1.2 is enabled, dereference works.
TLSv1.3-only is the Modern SSL configuration in the [Mozilla conf. generator](https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6). In addition, this indicates TLSv1.3 is currently not supported at all by the JSON schema validator implementation.

**Comment by JamesNK** [comment]
What version of .NET are you using? What OS?

**Comment by jakubklimek** [comment]
I used the https://www.jsonschemavalidator.net/ instance

**Comment by JamesNK** [comment]
Ok! I believe this will be fixed in the next couple of months - https://azure.github.io/AppService/2020/06/09/NET-Framework-4.8-is-coming-to-App-Service.html

.NET Framework supports TLS 1.3

**Comment by jakubklimek** [comment]
OK, thanks for the info. I guess this can be closed then.

**Comment by jakubklimek** [comment]
@JamesNK Hi, I was wondering, today, I ran again into the issue with TLS 1.3 only server - it still has not been fixed, at least on the https://www.jsonschemavalidator.net/ instance. What is the status about this?
