### ISSUE TITLE
Schema Hierarchy Request

### ISSUE THREAD

**Issue by fbarnard** [JamesNK/Newtonsoft.Json.Schema#23]
Hi

I am currently using Json.Schema more as a definition that a validation. I wrote a little wrapper around it to get things like parent and get a certain child with a path (jsonPath ish) and name of current without extentiondata but based on parent and so on.

Would it be possible to add some sort of Hierarchy like Jobject. So that you can go parent. Like i said not really using it as "here is json is it valid".

thanks

**Comment by JamesNK** [comment]
A schema can be referenced by multiple other schemas so a Parent property doesn't make sense.

**Comment by fbarnard** [comment]
Yes.

But a instance  of a ref to a schema  will only have one parent.

Or am I understanding  it wrong.

Thanks

On Monday, 7 September 2015, James Newton-King <notifications@github.com>
wrote:

> A schema can be referenced by multiple other schemas so a Parent property
> doesn't make sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/23#issuecomment-138374465>
> .
>


-- 
Francois D. Barnard
083 380 6645

**Comment by fbarnard** [comment]
Hi

Sorry Never mind I understand.

Thanks

On Monday, 7 September 2015, James Newton-King <notifications@github.com>
wrote:

> A schema can be referenced by multiple other schemas so a Parent property
> doesn't make sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/23#issuecomment-138374465>
> .
>


-- 
Francois D. Barnard
083 380 6645
