### ISSUE TITLE
ArgumentNullException when trying to call  public static bool IsValid(this JToken source, JSchema schema, out IList<ValidationError> errors)

### ISSUE THREAD

**Issue by maint16** [JamesNK/Newtonsoft.Json.Schema#238]
Hi, 
I got this error when trying to validate my schema: While "https://www.jsonschemavalidator.net" returned: "No errors found. JSON validates against the schema".
          "message": "Value cannot be null.\r\nParameter name: value",
           "type": "System.ArgumentNullException",
            "raw": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: value\r\n   at Newtonsoft.Json.JsonWriter.WriteToken(JsonToken token, Object value)\r\n   at Newtonsoft.Json.Schema.Infrastructure.Validation.Validator.ValidateCurrentToken(JsonToken token, Object value, Int32 depth)\r\n   at Newtonsoft.Json.Schema.JSchemaValidatingReader.ValidateCurrentToken()\r\n   at Newtonsoft.Json.Schema.SchemaExtensions.Validate(JToken source, JSchema schema, SchemaValidationEventHandler validationEventHandler)\r\n   at Newtonsoft.Json.Schema.SchemaExtensions.IsValid(JToken source, JSchema schema, IList`1& errors).

**Comment by JamesNK** [comment]
Hi

Please include your schema and the JSON you're validating with this issue. I need them to be able to figure out why you got an error.

**Comment by datnqvn** [comment]
Hi James, here is the code used to reproduce this issue:
- .net core 2.2
- Newtonsoft.Json" Version="12.0.3"
   Newtonsoft.Json.Schema" Version="3.0.13"
- Example code
Program.cs

            using System;
            using System.Collections.Generic;
            using Newtonsoft.Json.Linq;
            using Newtonsoft.Json.Schema;
            
            namespace ConsoleApp5
            {
                class Program
                {
                    static void Main(string[] args)
                    {
                        Console.WriteLine("Hello World!");
            
                        var schemaUrlResolver = new JSchemaUrlResolver();
                        var schemaReaderSettings = new JSchemaReaderSettings
                            {
                                Resolver = schemaUrlResolver,
                                Validators = new List<JsonValidator> { new CustomJsonValidator() { } }
                            };
                        JSchema schema = JSchema.Parse(@"{
                              ""$schema"": ""http://json-schema.org/draft-07/schema#"",
                              ""$id"": ""schema.json"",
                              ""title"": ""schema"",
                              ""description"": ""Schema of Object"",
                              ""type"": ""object"",
                              ""properties"": {
                                ""id"": {
                                  ""type"": ""integer""
                                }
                              },
                              ""additionalProperties"": false,
                              ""required"": [
                                ""id""
                              ]
                            }", schemaReaderSettings);
            
                        var model = new Model<string>( );
                        JObject obj = new JObject();
                        obj["id"] = model.Value;
                        Validate(obj, schema);
                    }
            
                    private static void Validate(JObject value, JSchema metadata)
                    {
            
                        try
                        {
                           var result = value.IsValid(metadata, out IList<ValidationError> errors);
                        }
                        catch (Exception exception)
                        {
                            Console.WriteLine("Exception!");
                            throw;
                        }
            
                    }
                }
            }
            
Model.cs
        using System;
        using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;
        using System.Text;
        
        namespace ConsoleApp5
        {
            public class Model<T>
            {
                #region Public
        
                /// <summary>   Gets or sets the validation result. </summary>
                /// <value> The validation result. </value>
                public T Value { get; set; }
        
                #endregion
            }
        }

CustomValidator
          using Newtonsoft.Json.Linq;
          using Newtonsoft.Json.Schema;
          
          namespace ConsoleApp5
          {
              public class CustomJsonValidator : JsonValidator
              {
          
                  public override bool CanValidate( JSchema schema )
                  {
                      return true;
                  }
          
                  public override void Validate( JToken value, JsonValidatorContext context )
                  {
                      // do anything
                  }
              }
          }

**Comment by haiphong238** [comment]
I have the same issue. Any updates?

**Comment by tunp88** [comment]
I am facing the same issue. Have anyone fixed it?

**Comment by sontiny** [comment]
Yes, I have the same issue like this. Does anyone solve the problem?

**Comment by HanhHongBui** [comment]
I have the same issue. Please help to fix.

**Comment by JamesNK** [comment]
Thanks. This will be fixed in the next version.
