### ISSUE TITLE
Type null values

### ISSUE THREAD

**Issue by fbarnard** [JamesNK/Newtonsoft.Json.Schema#24]
Hi

When i have a schema where the type field is not provided it return null(not JSchemaType.Null)  When i have type : null or type:"" it throws an exception. Should it not be set to JSchemaType.Null or JSchemaType.None for all the above cases.

Had a look at schema definition and there is a null but there is no real rules around it.

thanks

**Comment by JamesNK** [comment]
It you look at the JSON Schema Draft 4 spec you'll see that type with a null value isn't a valid schema.

```
{
	"type": null
}
```

**Comment by fbarnard** [comment]
HI

Cool. One more question on this if you dont provide a type field at all it currently makes the type null(not JSchemaType.Null) had a look at the definitions and could not find anything about default  will it not be better if  the type is set to JSchemaType.Null or event better JSchemaType.None.

thanks

**Comment by JamesNK** [comment]
The default is nothing which means all types. Null is fine.
