### ISSUE TITLE
Easy way to add '$ref' to Schema

### ISSUE THREAD

**Issue by KVerwold** [JamesNK/Newtonsoft.Json.Schema#25]
Hi,

I'm using your library, to create Json schema files automatically to all our DTO classes. I wasn't really amazed about using Data Annotations mixed with [JsonProperty] attributes, so I'm doing it via reflection myself. I'm building the schema,  by using the JSchema class and everything works fine. The one thing I'm missing is, to add a reference '$ref', to the other schema files, somehow to the schema. I cannot find any properties og functions from the specs from JSchema and I want to avoid, using a resolver, due to the build order of the schemas won't take care about the referencing inside the schemas. Can you help me out ?

Kind regards
Kristian

**Comment by JamesNK** [comment]
Just use a schema in multiple places, or place it in definitions, and it will be a $ref when the schema is written as JSON.
