### ISSUE TITLE
problem with enum validation error message in version 3.0.14, work fine in 3.0.13

### ISSUE THREAD

**Issue by Spirch** [JamesNK/Newtonsoft.Json.Schema#252]
in 3.0.14 if an enum value doesnt match the schema it give this validation error

**JSON does not match schema from '$ref'. Path 'valid/path', line XXXX position XX**

in 3.0.13 it give this message
**Value "X" is not defined in enum. Path '/valid/path/to/enum', line XXXX, position XX**

`The Value "X" is not defined in enum` is way better than `JSON does not match schema from '$ref'`

also the error in 3.0.13 give the line where the enum is used (property) while 3.0.14 give the line of the root object

it took me a few hours to debug a validation error, the object is complex, few hundred lines, properties, nested object, etc

not having the exact line like 3.0.13 make it very hard to find / spot the issue

if the behaviour would have been like 3.0.13, it would have taken me a few seconds instead of hours

right now i downgraded to 3.0.13

**Comment by JamesNK** [comment]
Hi

Could you add your JSON schema and JSON so I can reproduce your issue?

**Comment by Spirch** [comment]
yes, i was able to make a very small demo and while doing this i found it is related to the `description attribute`, when it's there 3.0.14 behave differently

if you remove this from the schema:
`            "description": "test",`
you get the proper behaviour under 3.0.14
if you keep it undr 3.0.13, it doesnt matter, it always work as expected

code first, result after

**this is a new console app under .net core 3.1, the only nuget is this schema one**

**data.json**
```
{
  "testEnum": [
    {
      "testEnum1": {
        "value": "21"
      }
    }
  ]
}
```
**schema.json**
```
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "testEnum": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/components/schemas/funTest"
      }
    }
  },
  "components": {
    "schemas": {
      "funTest": {
        "type": "object",
        "additionalProperties": false,

        "properties": {
          "testEnum1": {
            "description": "test",
            "$ref": "#/components/schemas/testEnum"
          }
        }
      },
      "testEnum": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "string",
            "enum": [
              "1",
              "2",
              "3"
            ]
          }
        }
      }
    }
  }
}
```
**code**
```

using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using System;
using System.Collections.Generic;
using System.IO;

namespace ConsoleApp21
{
    class Program
    {
        static void Main(string[] args)
        {
            JObject clientJson = JObject.Parse(File.ReadAllText("data.json"));
            JSchema schema = JSchema.Parse(File.ReadAllText("schema.json"));
            bool valid = clientJson.IsValid(schema, out IList<string> errorMessages);

            Console.WriteLine($"Valid? {valid}");

            foreach (var error in errorMessages)
                Console.WriteLine(error);

            Console.ReadKey();
        }
    }
}
```

**3.0.13 with description**
```
Valid? False
Value "21" is not defined in enum. Path 'testEnum[0].testEnum1.value', line 5, position 21.
```
**3.0.13 without description**
```
Valid? False
Value "21" is not defined in enum. Path 'testEnum[0].testEnum1.value', line 5, position 21.
```
**3.0.14 with description WRONG result**
```
Valid? False
JSON does not match schema from '$ref'. Path 'testEnum[0].testEnum1', line 4, position 20.
```

**3.0.14 without description**
```
Valid? False
Value "21" is not defined in enum. Path 'testEnum[0].testEnum1.value', line 5, position 21.
```

**Comment by JamesNK** [comment]
Hi

I investigated this and found it isn't a bug. In the latest version $ref is now a scope. That means the previous error message is now a child error. If you use the IsValid overload that returns `ValidationError` then you'll see it in the child errors.

If you don't like this then change this part of your schema:

```
          "testEnum1": {
            "description": "test",
            "$ref": "#/components/schemas/testEnum"
          }
```

...to this:
```
          "testEnum1": {
            "$ref": "#/components/schemas/testEnum"
          }
```
