### ISSUE TITLE
Portable net40?

### ISSUE THREAD

**Issue by kenbrubaker** [JamesNK/Newtonsoft.Json.Schema#26]
I tried to load this into a portable net40 project and it didn't work. It looks like you've added it to Newtonsoft.Json nuspec but not for schema. Will that be happening for schema too?

Ref: https://github.com/JamesNK/Newtonsoft.Json/blob/master/Build/Newtonsoft.Json.nuspec

Update: Oh, I see the problem. The Schema package is assigned to Newtonsoft.Json v6.0.8. Why hasn't it been updated along with Json.Net? Will it be?

**Comment by JamesNK** [comment]
I didn't create a portable net40 project for schema because I wanted to avoid having too many projects to maintain. Is it important for you? There is a portable net45 you could use.

**Comment by kenbrubaker** [comment]
I saw you supported two profiles in Newtonsoft.Json so I wondered about the discrepancy. I'm still trying to wrap my head around all these different ways to do portable libraries (dotnet anyone?). I'll try profile 259 (it's for xamarin) and see how it goes. Thanks!

Sorry for conflating two issues but: about my other question: Are you planning to bump Newtonsoft.Json.Schema to point to Newtonsoft.Json v7?

**Comment by JamesNK** [comment]
You can use it with v7 today, the minimum version is 6.0.8. Why do you want the minimum version to be v7?

**Comment by kenbrubaker** [comment]
K. Just making sure it works with v7.
