### ISSUE TITLE
SchemaVersion draft 2019-09 not working

### ISSUE THREAD

**Issue by rverspuij** [JamesNK/Newtonsoft.Json.Schema#262]
When calling:
`JSchema.Parse(<schema string>, new JSchemaReaderSettings() { ValidateVersion = true });`

on a `<schema string>` that contains "$schema": "https://json-schema.org/draft/2019-09/schema" I get an ArgumentNullException on StreamReader because  `....GetManifestResourceStream("Newtonsoft.Json.Schema.Resources.draft2019-09/schema.json");` in `SchemaVersionHelpers.LoadResourceSchema` returns null  (`...GetManifestResourceNames()` does not return this resource in its list; probably because the schema.json is in a sub folder draft2019-09).

**Comment by elgonzo** [comment]
It's a bug in the [project file](https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/master/Src/Newtonsoft.Json.Schema/Newtonsoft.Json.Schema.csproj):

https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/5a68513e38d899d49f0842ba82a2235154ce3c18/Src/Newtonsoft.Json.Schema/Newtonsoft.Json.Schema.csproj#L41

this erroneously prevents the schema file `Resources/draft2019-09/schema.json` from being included in the resources of the Json.Schema assembly (as it does not match the include file path pattern).

**Comment by JamesNK** [comment]
Thanks for reporting this. Fixed.

**Comment by alexmg** [comment]
I also came across this issue today. Will there be a release with this fix in the near future?
