### ISSUE TITLE
No validation extensiblity?

### ISSUE THREAD

**Issue by kenbrubaker** [JamesNK/Newtonsoft.Json.Schema#27]
I could find no extensibility point for schema validation. I was looking specifically for custom format validation, which is mentioned in the specs. I may also want to do custom validation at specific points, but there's no way to hook into the validation step either.

Have I missed something?

The open source golang implementation has support for custom format validation, for example:

[gojsonschema]( https://github.com/xeipuuv/gojsonschema)
> For repetitive or more complex formats, you can create custom format checkers

Also: Would you take pull requests for this?

**Comment by JamesNK** [comment]
Right now there isn't any hook for custom format validators. It sounds like a useful feature. Feel free to make a pull request. I'll likely change it before merging but it would be good to see what someone else comes up with.

**Comment by kenbrubaker** [comment]
K. Hope to in a couple of weeks.

**Comment by JamesNK** [comment]
The next version will support custom validators. You can create a custom format using this:

https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/1190f73a3c7d3dce5dc46bb8e85c49316040a8e8/Src/Newtonsoft.Json.Schema.Tests/JsonValidatorTests.cs#L104-L174
