### ISSUE TITLE
Question about description in json schema

### ISSUE THREAD

**Issue by marekott** [JamesNK/Newtonsoft.Json.Schema#290]
Hi @JamesNK,
does `Newtonsoft.Json.Schema` support out of the box converting comments from code into `description` fields during schema generation? I am aware of `Description` attribute and that it is mapped, however I am interested in behaviour similar to the one that `Swashbuckle` is offering where property documented like this would be put into schema with `"description": "Id of the entity."`:
```csharp
/// <summary>
/// Id of the entity.
/// </summary>
public Guid Id { get; }
```
If not are there any plans for such feature?

**Comment by JamesNK** [comment]
That isn't supported. This is the first time it has been suggested. There aren't plans to add it right now.

**Comment by marekott** [comment]
Ok, thanks.
