### ISSUE TITLE
V4 validation issue

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json.Schema#3]
From https://github.com/JamesNK/Newtonsoft.Json/issues/115#issuecomment-71037335

Hi James,

I've been doing some tests on the new v4 schema validation support and I come across an issue.  I'm sending JSON request to a well known web portal.  As part of their client validation process they provide a set of v4 schemas for the various request types they support and an valid example of each of the JSON requests so that users of their API can perform some sanity checks.
When I run their test requests through my code using Json.NET some of the requests fail validation.

The  portal says they have run the sample through http://json-schema-validator.herokuapp.com and 
and https://github.com/Julian/jsonschema . Both report no errors.  I've included below both the v4 schema and the test JSON request. This is the smallest request and schema that failed.  Json.Net reported the validation error in the errorList as:
"JSON is valid against more than oneschema from 'oneOf'. Valid schema indexes: 0, 1. Line 1, position 1.

JSON Request:

{
   "branch_reference" : "zpg_test_1",
   "branch_name" : "XXX Test Branch",
   "location" : {
      "property_number_or_name" : "65",
      "street_name" : "Some Street",
      "town_or_city" : "London",
      "postal_code" : "SEX 0HR",
      "country_code" : "GB"
   },
   "email": "members@xxx.co.uk",
   "website" : "http://www.xxx.co.uk/"
}

V4 Schema:

{
   "$schema" : "http://json-schema.org/draft-04/schema#",
   "title" : "branch/update",
   "type" : "object",
   "additionalProperties" : false,
   "id" : "http://realtime-listings.webservices.xxx.co.uk/docs/v0.1/schemas/branch/update.json",
   "definitions" : {
      "coordinates" : {
         "type" : "object",
         "additionalProperties" : false,
         "properties" : {
            "latitude" : {
               "type" : "number",
               "minimum" : -90,
               "maximum" : 90
            },
            "longitude" : {
               "type" : "number",
               "minimum" : -180,
               "maximum" : 180
            }
         },
         "required" : [
            "latitude",
            "longitude"
         ]
      }
   },
   "properties" : {
      "branch_name" : {
         "type" : "string",
         "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
      },
      "branch_reference" : {
         "type" : "string",
         "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
      },
      "email" : {
         "type" : "string",
         "pattern" : "@"
      },
      "location" : {
         "type" : "object",
         "additionalProperties" : false,
         "properties" : {
            "property_number_or_name" : {
               "type" : [
                  "integer",
                  "string"
               ],
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "street_name" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "locality" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "town_or_city" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "county" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "postal_code" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "country_code" : {
               "type" : "string",
               "pattern" : "^[A-Z]{2}(-[A-Z0-9]{1,3})?$"
            },
            "coordinates" : {
               "$ref" : "#/definitions/coordinates"
            },
            "paf_address" : {
               "type" : "object",
               "additionalProperties" : false,
               "properties" : {
                  "address_key" : {
                     "type" : "string",
                     "pattern" : "^[0-9]{8}$"
                  },
                  "organisation_key" : {
                     "type" : "string",
                     "pattern" : "^[0-9]{8}$"
                  },
                  "postcode_type" : {
                     "enum" : [
                        "L",
                        "S"
                     ]
                  }
               },
               "required" : [
                  "address_key",
                  "organisation_key",
                  "postcode_type"
               ]
            },
            "paf_udprn" : {
               "type" : "string",
               "pattern" : "^[0-9]{8}$"
            }
         },
         "required" : [
            "street_name",
            "town_or_city",
            "country_code"
         ]
      },
      "telephone": {
         "type" : "string",
         "pattern" : "[0-9]+"
      },
      "website" : {
         "type" : "string",
         "pattern" : "^[Hh][Tt][Tt][Pp][Ss]?://\\S+$"
      }
   },
   "required" : [
      "branch_reference",
      "branch_name",
      "location"
   ],
   "oneOf" : [
      { "$ref" : "#/constraints/gb" },
      { "$ref" : "#/constraints/overseas" }
   ],
   "constraints" : {
      "gb" : {
         "properties" : {
            "location" : {
               "properties" : {
                  "country_code" : {
                     "pattern" : "^GB"
                  },
                  "postal_code" : {
                     "pattern" : "^[A-PR-UWYZ][A-HJ-Y]?[0-9][0-9A-HJKMNPR-Y]? [0-9][ABD-HJLNP-UW-Z]{2}$"
                  }
               },
               "required" : [
                  "postal_code"
               ]
            }
         }
      },
      "overseas" : {
         "properties" : {
            "location" : {
               "properties" : {
                  "country_code" : {
                     "not" : {
                        "pattern" : "^GB"
                     }
                  }
               }
            }
         }
      }
   }
}

**Comment by JamesNK** [comment]
This is a bug. It should be fixed within the next day.

**Comment by br15** [comment]
Thanks for the very quick response.

**Comment by JamesNK** [comment]
Fixed. 1.0.2 is on NuGet
