### ISSUE TITLE
Localization error messages

### ISSUE THREAD

**Issue by tvilkov** [JamesNK/Newtonsoft.Json.Schema#30]
It would be great to have an ability to localize error messages.

**Comment by JamesNK** [comment]
Hi

I'm afraid I don't have the resources to localize error messages. However all the information used to construct a validation error message is available on the `ValidationError` object. Using properties on it you can put together your own error messages that are localized to your application's culture.

An example that returns a collection of ValidationErrors is under the Detailed Validation Information section here - http://www.newtonsoft.com/jsonschema/help/html/ValidatingJson.htm
