### ISSUE TITLE
prefixItems of 2020-12 not supported

### ISSUE THREAD

**Issue by jakubklimek** [JamesNK/Newtonsoft.Json.Schema#306]
In JSON Schema draft 2020-12, [tuple validation](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation) uses `prefixItems` and `items` keywords instead of `items` and `additionalItems`. This is currently not supported by https://www.jsonschemavalidator.net/

**Comment by JamesNK** [comment]
Now supported.
