### ISSUE TITLE
Status of this project (draft 2020-12)

### ISSUE THREAD

**Issue by elitemike** [JamesNK/Newtonsoft.Json.Schema#315]
My project is currently using the JSchemaValidatingReader.  We can't easily switch to system.text.json unless something equivalent is built into the library to support our data structure.  We stream read large data sets and yield return each item in entries.  Due to our structure, we can't rely on the UTF8JsonReader to just enumerate async.  UTF8JsonReader also does not allow a yield return.  

Is this project dead or can we expect an update to 2020-12 as well as future versions??
```
[
    {
        "metadata":{
            "id": "test",
            "type": "Log",
            "dates": [
                {
                    "timestamp": "asdfasdf",
                    "type": "asdfasdf"
                }
            ]
        },
        "entries":[
            {
                "text": "alpha",
                "level":  "Info",
                "type": "A"               
            },
            {
                "text": "alpha",
                "level": "Info",
                "type": "B"               
            }
        ]
    }
]
```

**Comment by vigouredelaruse** [comment]
i will venture an answer.

it's a risk taking a dependency on something listed on github by a single person organization. 

however if the tool is worth taking a dependency, it's probably worth taking ownership of blocking issues affecting one's work by forking the repo 

the first time i did this it felt like taking on tangental work, but it's not when your merged updates to the fork unblock your main project

felicitations
