### ISSUE TITLE
JsonObject to JSchema

### ISSUE THREAD

**Issue by bbowyersmyth** [JamesNK/Newtonsoft.Json.Schema#32]
I have loaded a swagger file (eg http://petstore.swagger.io/v2/swagger.json) into a JsonObject which contains json schema definitions for the return types.
The return schema of say [GET]/pet/{petId} is "#/definitions/Pet", what is the best way to turn those JsonObjects into JSchema versions. Those schemas can also contain Json pointers (see "Pet") so I'm not sure if loading from a JTokenReader is going to work?

**Comment by JamesNK** [comment]
I'm assuming you mean JObject to JSchema.

You could do something like:

```
JObject o = JObject.Parse(swagger.json);

JSchema pet = JSchema.Load(o["definitions"]["Pet"].CreateReader());
```

**Comment by JamesNK** [comment]
This works - https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/a512a3d29dbcdc4e20065eb23a7bd27b443beba4/Src/Newtonsoft.Json.Schema.Tests/Issues/Issue32Tests.cs

**Comment by bbowyersmyth** [comment]
Thanks James, that did the trick.

**Comment by IanKemp** [comment]
The example linked above should really be present on https://www.newtonsoft.com/jsonschema/help/html/LoadingSchemas.htm
