### ISSUE TITLE
Refs to "#" don't parse from a common definition

### ISSUE THREAD

**Issue by LoungeFlyZ** [JamesNK/Newtonsoft.Json.Schema#33]
I have a schema that has a 'manager' property which is a user object:
```
"manager": {
  "anyOf": [{
    "$ref": "#/definitions/user"
  }],
  "title": "Manager"
}
```
The #/definitions/user schema is:
```
"definitions": {
  "user": {
    "$ref": "#"
  }
}
```
This results in a "Error when resolving schema reference '#'. Path 'definitions.user'" error.

Addressing the user with "$ref": "#" from the manager property isn't an option as we are using the definition to help build the UI and need a common definition.

**Comment by JamesNK** [comment]
This appears to work:

```
{  
  "properties":{  
    "manager":{  
      "anyOf":[  
        {  
          "$ref":"#/definitions/user"
        }
      ],
      "title":"Manager"
    }
  },
  "definitions":{  
    "user":{  
      "$ref":"#"
    }
  }
}
```

**Comment by LoungeFlyZ** [comment]
Interesting ... when including an ID field like this it doesn't:

```
{
    "id": "foo.com/schemas/user",
    "properties": {
        "manager": {
            "anyOf": [{
                "$ref": "#/definitions/user"
            }],
            "title": "Manager"
        }      
    },
    "definitions": {
        "user": {
            "$ref": "#"
        }  
    }
}
```

**Comment by LoungeFlyZ** [comment]
ok ... adding http:// to my "id" seems to fix things.  Looks like an invalid URI is throwing this off.

**Comment by JamesNK** [comment]
Without the scheme it is a not an absolute id. You would need `"$ref": "foo.com/schemas/user"` to reference it.

**Comment by LoungeFlyZ** [comment]
Thanks for the help!!
