### ISSUE TITLE
Regular expressions validation and JSON Schema specification

### ISSUE THREAD

**Issue by zloster** [JamesNK/Newtonsoft.Json.Schema#34]
The JSON Schema specification ~~requires~~ (edited) recommends the regular expressions to be [ECMA 262 compliant](http://json-schema.org/latest/json-schema-validation.html#anchor6). The [grammar](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-patterns) for ECMA 262 specification.
The problem is that current implementation validates _successfully_ schemas with the following regexp: `"pattern" : "^\\S(|(.|\\n)*\\S)\\Z"`, which is _not_ ECMA 262 compliant (`'\Z'` is not special literal).
The problem is reproducible in the [online version](http://www.jsonschemavalidator.net/#).
[Example schema](https://realtime-listings.webservices.zpg.co.uk/docs/latest/schemas/listing/delete.json):
```
{
   "$schema" : "http://json-schema.org/draft-04/schema#",
   "title" : "listing/delete",
   "type" : "object",
   "additionalProperties" : false,
   "id" : "http://realtime-listings.webservices.zpg.co.uk/docs/v1.1/schemas/listing/delete.json",
   "properties" : {
      "listing_reference" : {
         "type" : "string",
         "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
      },
      "deletion_reason" : {
         "enum" : [
            "withdrawn",
            "offer_accepted",
            "exchanged",
            "completed",
            "let"
         ]
      }
   },
   "required" : [
      "listing_reference"
   ]
}
```
Example request:
```
{
 "listing_reference":"d"
}
```

**Comment by JamesNK** [comment]
There is no way to realistically fix this since the library just uses System.Text.RegularExpressions. If Microsoft improves their regex support then it will get included.

**Comment by zloster** [comment]
IMO Microsoft has support for the `ECMAScript` regexes.
According to [Microsoft documentation](https://msdn.microsoft.com/en-us/library/yd1hzczs%28v=vs.110%29.aspx) both `.NET Framework 4` and `.NET Framework 4.5` have support for `ECMAScript` option for the `System.Text.RegularExpressions` namespace.
This software seems to support `.NET 4` and `.NET 4.5` according to [this documentation](http://www.newtonsoft.com/jsonschema/help/html/Introduction.htm):

> Supports .NET 4, .NET 4.5, Windows Phone, Windows Store, Mono, and Xamarin

**Comment by JamesNK** [comment]
I wasn't aware of that. I'll take a look at whether setting the ECMAScript option improves compatibility.

**Comment by zloster** [comment]
I've missed the fact that the `ECMAscript` regular expressions are **recommendation** not **requirement** (check the comment [here](https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/119#issuecomment-230742558)).
Accept my apology.
I've edited the title and my initial comment.
Given the new information I think that just adding some information in the documentation about the supported regular expressions will be good enough.
