### ISSUE TITLE
Nullability of `JSchemaGenerationProvider.GetSchema` return is incorrect

### ISSUE THREAD

**Issue by JR-Morgan** [JamesNK/Newtonsoft.Json.Schema#341]
The [`Newtonsoft.Json.Schema.Generation.JSchemaGenerationProvider.GetSchema(JSchemaTypeGenerationContext)`](https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/05524f9972c75648c7af40e99240f2280c03dc16/Src/Newtonsoft.Json.Schema/Generation/JSchemaGenerationProvider.cs#L20C43-L20C72) return type is incorrectly typed as a non-nullable `JSchema`

The XML comment for the function clearly says that `null` is a valid return value, so the return type should be `JSchema?`

i.e.
```cs
  public abstract JSchema? GetSchema(JSchemaTypeGenerationContext context);
```

This is a problem for users implementing `GetSchema` and wanting to return null, as they will either see a [CS8603 - Possible null reference return](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference) or a [CS8764 - Nullability of return type doesn't match overridden member (possibly because of nullability attributes](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration) depending on nullability syntax.

**Comment by JamesNK** [comment]
The XML doc comment is probably the incorrect one here.

The intent of the type is `CanGenerateSchema` is called to check that the provider can generate for a type, and then `GetSchema` always returns a value.

Non-null is checked for here: https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/05524f9972c75648c7af40e99240f2280c03dc16/Src/Newtonsoft.Json.Schema/Generation/JSchemaGeneratorInternal.cs#L247-L252
But not checked for here:
https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/05524f9972c75648c7af40e99240f2280c03dc16/Src/Newtonsoft.Json.Schema/Generation/JSchemaGeneratorInternal.cs#L272-L273

I think the change to make is to improve the XML doc and check that `GetSchema` doesn't return null in an extra place.

What do you think?

**Comment by cdriesler** [comment]
For a bit more context (unsure either way) the example [here](https://www.newtonsoft.com/jsonschema/help/html/CreateCustomProvider.htm) also suggests using `null` as a way to fall back to using default generation.

**Comment by JamesNK** [comment]
Thanks. I looked into it more and you're right that this should allow null. Fixing here: https://github.com/JamesNK/Newtonsoft.Json.Schema/pull/342

It might be some time before the next release so you'll need to suppress the warning for now.
