### ISSUE TITLE
Not able to see Model Validation

### ISSUE THREAD

**Issue by MateenKadwaikar** [JamesNK/Newtonsoft.Json.Schema#35]
After using this library I was not able to see the model validation message which was define in Class Property.

 [DataContract]
    public class Request
    {
        [DataMember]
        [Required(ErrorMessage = Constants.ModelError.VersionRequired, AllowEmptyStrings = true)]
        [RegularExpression(Constants.RegularExpressionVersion, ErrorMessage = Constants.ModelError.VersionInvalid)]
        [MinLength(1, ErrorMessage = Constants.ModelError.VersionInvalid)]

        public string Version { get; set; }
}

Not able to see this error message.

**Comment by JamesNK** [comment]
Hi

Unfortunately JSON Schema doesn't have any support for customizing error messages. If they add it in the future then I'll add support for it to Json.NET Schema.
