### ISSUE TITLE
Custom JSchemaGenerationProvider does not run on all nodes.

### ISSUE THREAD

**Issue by jnathanh** [JamesNK/Newtonsoft.Json.Schema#36]
When I write a custom JSchemaGenerationProvider, it only modifies the parent node, whereas [the example in the documentation][1] indicates that it should run on every node.  In this specific example, I am trying to add a title attribute to every node.

    class User {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
    }
    
    class TitleProvider : JSchemaGenerationProvider {
        public override JSchema GetSchema(JSchemaTypeGenerationContext context) {
            var schema = new JSchemaGenerator().Generate(context.ObjectType);
            schema.Title = "foo";
            return schema;
        }
    }
    
    public class Program {
        public static void Main() {
            var generator = new JSchemaGenerator();
            generator.GenerationProviders.Add(new TitleProvider());
            var schema = generator.Generate(typeof(User));
    
            Console.WriteLine(schema);
        }
    }
    // OUTPUT:
    //{
    //  "title": "foo",
    //  "type": "object",
    //  "properties": {
    //    "Id": {
    //      "type": "integer"
    //    },
    //    "Name": {
    //      "type": [
    //        "string",
    //        "null"
    //      ]
    //    },
    //    "CreatedDate": {
    //      "type": "string"
    //    }
    //  },
    //  "required": [
    //    "Id",
    //    "Name",
    //    "CreatedDate"
    //  ]
    //}

Other Notes:

 - if I return null from the TitleProvider `GetSchema` method, it does iterate over all the properties (which I observed in debugger), but then it's not adding a title. But it skips the child nodes (in debugger) when I return a JSchema.

  [1]: http://www.newtonsoft.com/jsonschema/help/html/CreateCustomProvider.htm

**Comment by JamesNK** [comment]
Your issue is the child nodes are being generated without the `TitleProvider` here:

```
var schema = new JSchemaGenerator().Generate(context.ObjectType);
```

**Comment by jnathanh** [comment]
Right, but adding the title provider creates an infinite loop.  

I debugged through the source code to figure out what was happening and it looks like your intent with the providers (if I understand it correctly) was that for any type the providers act on, the provider is responsible for populating the entire schema for that type and it's properties.  I thought it was was adding functionality to the schema, instead it is replacing it.  So I just misunderstood the purpose of the providers.

I did want all of the default behavior on each node however, so I figured out a workaround (below).  It would be nice if this kind of functionality was included out of the box.  I'd be happy to help contribute if you point me in the right direction.

    abstract class RecursiveProvider : JSchemaGenerationProvider {
        public string SkipType { get; set; }
        public override JSchema GetSchema(JSchemaTypeGenerationContext context) {
            var type = context.ObjectType;
            JSchema schema = null;
    
            var generator = new JSchemaGenerator();
    
            var isObject = type.Namespace != "System";
    
            if (isObject) {
                if (SkipType == type.Name)
                    return null;
    
                this.SkipType = type.Name;
                generator.GenerationProviders.Add(this);
            }
    
            schema = generator.Generate(type);
            return ModifySchema(schema, context);
        }
    
        public abstract JSchema ModifySchema(JSchema schema, JSchemaTypeGenerationContext context);
    
    }
    
    class PropertyProvider : RecursiveProvider {
        public override JSchema ModifySchema(JSchema schema, JSchemaTypeGenerationContext context) {
            schema.Title = "My Title";
            return schema;
        }
    }


```

**Comment by JamesNK** [comment]
Hi

I've fix this recursive stackoverflow issue - https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/master/Src/Newtonsoft.Json.Schema.Tests/Issues/Issue36Tests.cs

It will be available in the next release.
