### ISSUE TITLE
Quota Limit checker does not reset

### ISSUE THREAD

**Issue by kaustria** [JamesNK/Newtonsoft.Json.Schema#37]
Have requested to purchase a license soon, but in the meantime while working on a prototype, I keep running into the quota limit. 

Could there be an issue with the counter for the generator? Calling the generate method after more than an hour yields the same error. 

`The free-quota limit of 10 schema generations per hour has been reached. Please visit http://www.newtonsoft.com/jsonschema to upgrade to a commercial license.`

I did wonder if the schema itself causes the generator to call the generate method more than 10 times. 
I implemented a custom `JSchemaGenerationProvider` that handles the format if the property is of a certain type, but I do get the quota message prior to hitting a breakpoint in the overridden `GetSchema` method.

**Comment by Vaevictus** [comment]
i have this problem too, and the website says:
AGPL 3.0	Free with limitations (1000 validations per hour)

having the 10 schema validations per hour limit makes debugging code difficult. I dont see why you would have such a large validation limit and such a small generation limit...

**Comment by JamesNK** [comment]
Hi @kaustria 

Are you calling Generate on a type inside your custom JSchemaGenerationProvider? I think that contributes to the generated count.

**Comment by JamesNK** [comment]
I've fixed calling Generate on a type inside a custom JSchemaGenerationProvider contributing to the count. It will be in the next release.

**Comment by sarah-appsheet** [comment]
I am evaluating Json.Schema to see if it will work for a company project, but even with the latest NuGet package I get the error "the free-quota limit of 10 schema generations per hour has been reached." Even after rebuilding and re-running the next day. My company's not prepared to buy a license until I make sure it will meet our needs, but I can't continue experimenting with it at the moment. Any ideas would be much appreciated!

**Comment by JamesNK** [comment]
Hi

This bug fixed calling Generate on a type inside a custom JSchemaGenerationProvider contributing to the count.  There is still an overall limit of 10 generations per hour.

How many are you trying to do?

**Comment by sarah-appsheet** [comment]
I think I found the problem: in my custom JSchemaGenerationProvider, I'm generating a schema for each sub-object before adding custom attributes to it. Recursion, of course!

I'll comb through the documentation again to see if I can't find another way to include those custom attributes (display name, string enums with spaces, etc.) without calling JSchemaGenerationProvider repeatedly.

**Comment by JamesNK** [comment]
You can call Generate on the context parameter to GetSchema. That doesn't count since it is part of the same schema.

**Comment by sarah-appsheet** [comment]
Ah, thank you!

**Comment by knuxbbs** [comment]
> You can call Generate on the context parameter to GetSchema. That doesn't count since it is part of the same schema.

@JamesNK is this still true? I'm using the `Generator` from `context` parameter, and I'm still having this issue. Also, I saw that there isn't any check if the type is part of the same schema.

```c#
public virtual JSchema Generate(Type type, bool rootSchemaNullable)
{
    ValidationUtils.ArgumentNotNull(type, nameof(type));

    LicenseHelpers.IncrementAndCheckGenerationCount();

    Required required = rootSchemaNullable ? Required.AllowNull : Required.Always;

    JSchemaGeneratorInternal generator = new JSchemaGeneratorInternal(this);
    return generator.Generate(type, required);
}
```
