### ISSUE TITLE
Calling ToString on a JSchema object does not fully expand all references

### ISSUE THREAD

**Issue by Impl0x** [JamesNK/Newtonsoft.Json.Schema#38]
I am running into issues when I try to get a string representation of a JSchema when the schema file it was created from contains multiple of the same reference.

For example, suppose I have a `definitions.json` file:
```javascript 
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "sampleValue": {
    "title": "This is a sample value",
    "type": "string",
  },
  "sampleValueContainer": {
    "title": "This holds an item of sample value",
    "type": "object",
    "properties": {
      "value": {"$ref": "#/sampleValue"},
    }
  }
}
```
and a `test_object.json` file
```javascript
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "title": "Test Object",
  "type": "object",
  "properties": {
    "container": { "$ref": "/definitions.json#/sampleValueContainer" },
    "value": { "$ref": "/definitions.json#/sampleValue"}
  }
}
```

Since `sampleValueContainer` includes a `sampleValue`, the `test_object` schema references `sampleValue` twice. However, when I load `test_object.json` into a JSchema object and call ToString, I get the following output:
```javascript
{
  "title": "Test Object",
  "type": "object",
  "properties": {
    "container": {
      "title": "This holds an item of sample value",
      "type": "object",
      "properties": {
        "value": {
          "title": "This is a sample value",
          "type": "string"
        }
      }
    },
    "value": {
      "$ref": "#/properties/container/properties/value"
    }
  }
}
```

The value field, rather than being expanded out into the `sampleValue` subschema, is just replaced with an internal reference. For what I am doing it's important that the string I produce contain no internal or external references.

Is this replacement functionality intended? I haven't been able to find documentation related to the replacement of an external ref with an internal ref, nor have I been able to find a way to easily expand internal references in the JSchemas. 

Thanks!

**Comment by JamesNK** [comment]
Right now multiple references to the same schema are always be written as references. If there is more interest in this a setting to always write schemas as values rather than references.

**Comment by JamesNK** [comment]
Hi

I've added a new setting when writing schemas that allows you to control whether references are written. It will be in the next release. I'll post here again to let you know when it is out

https://github.com/JamesNK/Newtonsoft.Json.Schema/compare/aca57a048d891c5e9428b23f0c35fb2bc3057c63...7b564a5b65729482f84bcb74d42324930514149b
