### ISSUE TITLE
Nullable Property of Enum type breaks validation

### ISSUE THREAD

**Issue by dmikov** [JamesNK/Newtonsoft.Json.Schema#39]
Generated schema on type containing nullable enum type Property. All validation attempts on objects with the property actually set to null fail. I am using 9.0.1 json and latest 2.3 schema. Below is the code (made in LinqPad) sorry tried to use .netfiddle, but it doesn't work with v9 Json. The schema itself looks legit. So I guess the issue is in validation?

Also worth noting that setting `DefaultRequired` makes no difference on schema content.
```
void Main()
{
	var generator = new JSchemaGenerator() { DefaultRequired = Required.AllowNull};
	  var schema = generator.Generate(typeof(TestClass));
	  //schema.ToString().Dump();
	  
	  var testObject = new TestClass();
	  var jObject = JObject.FromObject(testObject);
	  jObject.Validate(schema);
}

public class TestClass
{
	public int Counter { get; set; }
	public TestEnum? TestProperty { get; set; }
}

public enum TestEnum
{ 
	none,one,two
}

//{
//	"type": "object",
//  "properties": {
//		"Counter": {
//			"type": "integer"
//	    },
//    "TestProperty": {
//			"type": [
//	          "integer",
//	          "null"
//      ],
//      "enum": [
//        0,
//        1,
//        2
//      ]
//    }
//  },
//  "required": [
//    "Counter",
//    "TestProperty"
//  ]
//}
```

**Comment by JamesNK** [comment]
I think the issue is the generated schema. For an enum to be valid the value has to be in the enum. The enum should end up looking like:

      "enum": [
        null,
        0,
        1,
        2
      ]

**Comment by JamesNK** [comment]
The alternative is two schemas for the property, via a oneOf. One would allow null, the other would be integer + the enum constraint.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/ec9f23baecd5e886d4c81aebd5da3bb4027aba52
