### ISSUE TITLE
Generating schema for self-referencing abstract types

### ISSUE THREAD

**Issue by rsheptolut** [JamesNK/Newtonsoft.Json.Schema#48]
Right now, `JSchemaGenerator` generates schema for abstract types as if they are normal types: `JSchemaGenerator` simpy enumerates its properties.

It would be better if the generated schema somehow accounted for the possibility of the value to be one of the descendants of the abstract type.

For example, I have a `Dictionary<string, BlockBase>` and I want the corresponding json object to consist of the properties with the values of `BlockBase` descendants and **only** of them. Also I want all the complex machinery of json validation to "propagate inside" those descendant classes and their properties.

As if it's not complicated enough, in my case I want the property names (a `string` in that dictionary) to determine the type of the object. And not just property names, but property name regex patterns. I did try to implement just this using a `JSchemaGenerationProvider`, and it almost worked, but it seems that JSchemaGenerationProvider doesn't give me an ability to work with circular "references".

Here's what I mean by "circular references". Below is my simplified structure and the implementation of `JSchemaGenerationProvider` that never stops being called.

```c#
internal class MyRootJsonClass
{
    public Dictionary<string, BlockBase> Blocks { get; set; }
}

internal abstract class BlockBase
{
    // Removed from sample: a hundred of other properties

    public Dictionary<string, BlockBase> NestedBlocks { get; set; }
}

// Removed from sample: a hundred descendants of BlockBase

internal class MyJSchemaGenerationProvider : JSchemaGenerationProvider
{
    public override JSchema GetSchema(JSchemaTypeGenerationContext context)
    {
        var schema = new JSchema();
        var descendants = Assembly.GetExecutingAssembly().GetTypes().Where(item => !item.IsAbstract && typeof(BlockBase).IsAssignableFrom(item)).ToList();
        foreach (var descendant in descendants)
        {
            // The line below never exits, because it's calling MySchemaGenerator.GetSchema again with the same parameter
            var descendantSchema = context.Generator.Generate(descendant);
            schema.PatternProperties.Add(descendant.Name + ".*", descendantSchema);
        }
        schema.AllowAdditionalProperties = false;
        schema.Type = JSchemaType.Object;
        return schema;
    }

    public override bool CanGenerateSchema(JSchemaTypeGenerationContext context)
    {
        return context.ObjectType == typeof(Dictionary<string, BlockBase>);
    }
}
```

The "endless cycle" can be kinda solved with introducing some fields to my class and somehow caching values in them (to get only the first "level of recursion"), but it would not be a complete solution to the problem.

### Summary
So, either I'm not really bright, or Newtonsoft.Json.Schema needs some mechanism to overcome these kinds of "circular references" when generating schemas.
Also, it would be great if adding support of generating schema for abstract types would be a little more straightforward.

Sorry for a long read. I'll be happy to clarify.

**Comment by rsheptolut** [comment]
I thought of a way to overcome the circular reference thingy with some trickery: 
```C#
internal class MyJSchemaGenerationProvider : JSchemaGenerationProvider
{
    private Dictionary<string, JSchema> _patternProperties;
    
    private readonly List<JSchema> _schemasToFinalize = new List<JSchema>();
    
    public override JSchema GetSchema(JSchemaTypeGenerationContext context)
    {
        var schema = new JSchema();
        if (_patternProperties == null)
        {
            _patternProperties = new Dictionary<string, JSchema>();
            // Guarantee that this code will be run only once per generation
            var descendants = Assembly.GetExecutingAssembly().GetTypes()
                .Where(item => !item.IsAbstract && typeof(BlockBase).IsAssignableFrom(item));
            _patternProperties = descendants.ToDictionary(descendant => descendant.Name + ".*", 
                descendant => context.Generator.Generate(descendant));
        }
        else
        {
            _schemasToFinalize.Add(schema);
        }
        schema.AllowAdditionalProperties = false;
        schema.Type = JSchemaType.Object;
        return schema;
    }

    public override bool CanGenerateSchema(JSchemaTypeGenerationContext context)
    {
        return context.ObjectType == typeof(Dictionary<string, BlockBase>);
    }
    
    public void FinalizeGeneration()
    {
        foreach (var schema in _schemasToFinalize)
        {
            schema.PatternProperties.Add(_patternProperties);
        }
    }
}

// Usage:
public class Test
{
    public void TestThis()
    {
        var generator = new JSchemaGenerator();
        var provider = new MyJSchemaGenerationProvider();
        generator.Providers.Add(provider);
        var schema = generator.Generate(typeof(MyRootJsonClass));
        provider.FinalizeGeneration();
        // _now_ the schema variable is ready to use
    }
}
```

Haven't had time to test this code yet, but I think it will do. So the problem seems to be solved, but the solution isn't pretty. It would only get worse if one had tried to implement a more complicated version of this, dealing not only with one single `BlockBase` type, but with any abstract type. 

Something to think about maybe, to improve the design of `Newtonsoft.Json.Schema.Generation` classes.

**Comment by rsheptolut** [comment]
Still need a little help! The thing I thought of is not working. The problem in short is, that I can't just add a reference to the schema in the patternproperties of itself. It copies the object or something, resulting in endlessly collecting the schema. I need a schema for JSON with possibly infinite recursion, but the condition for that property which can then contain a property of the same schema (and so on) is a regex. In my case, FinalizeGeneration runs for a _very_ long time, because adding a schema as a new new pattern property takes exponentially more and more time, because it contains more instances of itself.
To be clear: just want to specify a #ref to the schema for Dictionary<string, BlockBase> inside one of its properties (by regex). I think it's impossible to explicitly specify #ref, and I'm just adding the same schema object for all such properties, but it doesn't work because it seems Newtonsoft.JsonSchema copies the objects internally and piles them up to form a huge unsustainable tree.

**Comment by JamesNK** [comment]
I tried to repo this but I didn't get an exception

        internal class MyRootJsonClass
        {
            public Dictionary<string, BlockBase> Blocks { get; set; }
        }

        internal abstract class BlockBase
        {
            // Removed from sample: a hundred of other properties

            public Dictionary<string, BlockBase> NestedBlocks { get; set; }
        }

        internal class Block1 : BlockBase
        {

        }

        // Removed from sample: a hundred descendants of BlockBase

        internal class MyJSchemaGenerationProvider : JSchemaGenerationProvider
        {
            public override JSchema GetSchema(JSchemaTypeGenerationContext context)
            {
                var schema = new JSchema();
                var descendants = Assembly.GetExecutingAssembly().GetTypes().Where(item => !item.IsAbstract && typeof(BlockBase).IsAssignableFrom(item)).ToList();
                foreach (var descendant in descendants)
                {
                    // The line below never exits, because it's calling MySchemaGenerator.GetSchema again with the same parameter
                    var descendantSchema = context.Generator.Generate(descendant);
                    schema.PatternProperties.Add(descendant.Name + ".*", descendantSchema);
                }
                schema.AllowAdditionalProperties = false;
                schema.Type = JSchemaType.Object;
                return schema;
            }

            public override bool CanGenerateSchema(JSchemaTypeGenerationContext context)
            {
                return context.ObjectType == typeof(Dictionary<string, BlockBase>);
            }
        }

        [Test]
        public void JSchemaGenerationProvider_SelfReferencingAbstractType()
        {
            JSchemaGenerator generator = new JSchemaGenerator();
            generator.GenerationProviders.Add(new MyJSchemaGenerationProvider());
            JSchema schema = generator.Generate(typeof(MyRootJsonClass));

            Console.WriteLine(schema.ToString());
        }

Result:

```
{
  "definitions": {
    "Block1": {
      "type": "object",
      "properties": {
        "NestedBlocks": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "Block1.*": {
              "$ref": "#/definitions/Block1"
            }
          }
        }
      },
      "required": [
        "NestedBlocks"
      ]
    }
  },
  "type": "object",
  "properties": {
    "Blocks": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "Block1.*": {
          "$ref": "#/definitions/Block1"
        }
      }
    }
  },
  "required": [
    "Blocks"
  ]
}
```

**Comment by rsheptolut** [comment]
@JamesNK Weird... Thanks, I'll try to investigate further. I did't check my simplified case myself at all, I checked only my real case, and I just thought I included all of its aspects in the simplified one. My bad. I'll get back to you as soon as I figure out a real defective sample or that I'm a hack.

**Comment by rsheptolut** [comment]
@JamesNK I finally got the repro for you. Sorry for failing to do so from the beginning.

Your sample is almost what triggers it, though. You just need to add another single BlockBase descendant like this:
```c#
internal class Block2 : BlockBase
{

}
```

And the hell breaks loose:
```json
{
  "definitions": {
    "Block2": {
      "type": "object",
      "properties": {
        "NestedBlocks": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "Block1.*": {
              "type": "object",
              "properties": {
                "NestedBlocks": {
                  "type": "object",
                  "additionalProperties": false,
                  "patternProperties": {
                    "Block1.*": {
                      "$ref": "#/definitions/Block2/properties/NestedBlocks/patternProperties/Block1.*"
                    },
                    "Block2.*": {
                      "$ref": "#/definitions/Block2"
                    }
                  }
                }
              },
              "required": [
                "NestedBlocks"
              ]
            },
            "Block2.*": {
              "$ref": "#/definitions/Block2"
            }
          }
        }
      },
      "required": [
        "NestedBlocks"
      ]
    },
    "Block1": {
      "$ref": "#/definitions/Block2/properties/NestedBlocks/patternProperties/Block1.*"
    }
  },
  "type": "object",
  "properties": {
    "Blocks": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "Block1.*": {
          "$ref": "#/definitions/Block2/properties/NestedBlocks/patternProperties/Block1.*"
        },
        "Block2.*": {
          "$ref": "#/definitions/Block2"
        }
      }
    }
  },
  "required": [
    "Blocks"
  ]
}
```

It's counter-intuitive that adding another BlockBase descendant will end up generating schema like this.
__And it escalates quickly from there__. It practically stays forever in the loop in my case, where there are 23 descendants of BlockBase class.

Is it a bug or I'm just not cooking it right?

**Comment by JamesNK** [comment]
I've made some changes so that the generated JSON looks a little cleaner https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/324b304eacdbfe76de7878c10a83245049b8e931

Note that you'll want to change the generator so that dictionaries can be referenced:

```
JSchemaGenerator generator = new JSchemaGenerator();
generator.SchemaReferenceHandling = SchemaReferenceHandling.All;
generator.GenerationProviders.Add(new MyJSchemaGenerationProvider());
```

**Comment by JamesNK** [comment]
Now available - https://www.nuget.org/packages/Newtonsoft.Json.Schema/2.0.7
