### ISSUE TITLE
compile from source

### ISSUE THREAD

**Issue by krisrok** [JamesNK/Newtonsoft.Json.Schema#5]
how can i compile the current version? during my tinkering i've learned about friend assemblies which was nice :) but i didn't manage to resolve lots of the compiler errors. can you point me in the right direction? 

i'm really excited about the new ResolveSchemaContext but as said, i couldn't get it to work.

**Comment by JamesNK** [comment]
The Json.NET reference needs to be the unsigned one from the Json.NET Unsigned myget feed. Unfortunately this is a limitation of how friend assemblies work.

I'll be releasing a new version with better support for custom schema resolvers soon.
