### ISSUE TITLE
Cannot generate schema of type that uses [JsonConverter] class attribute

### ISSUE THREAD

**Issue by Vaevictus** [JamesNK/Newtonsoft.Json.Schema#51]
I am having a weird problem where I cant generate a schema for some of my dto classes.

any classes that derive from an abstract class that is decorated with [JsonConverter(MyCustomConverter)] fail without an exception. The schema generated is {{}}
I use the JSONConverter to control the deserialization of json objects posted to my web api from my clients, and I dont see how this should be intefering of generating the schema from the type.

Any ideas?

**Comment by JamesNK** [comment]
Hi, I tried a number of scenarios but couldn't recreate this - https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/8a51e1719affb289939b7f856b0f97dfbc362929

Could you post the class you're generating a schema for and the code you're using with JSchemaGenerator?

**Comment by Vaevictus** [comment]
Hi James, I will try and knock something together today to try and replicate it outside of my project and post here

**Comment by Vaevictus** [comment]
So I put together something that simulates my set up:

`using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Newtonsoft.Json.Schema.Tests.TestObjects
{
    public class DerivedClass1 : AbstractClassWithJsonConverterAttribute
    {
        public string Prop1 { get; set; }
        public bool Prop2 { get; set; }

        private string typeIdentifier = "DerivedClass1";
        public override string TypeIdentifier
        {
            get
            {
                return typeIdentifier;
            }

            set
            {
                typeIdentifier = value;
            }
        }
    }

    public class DerivedClass2 : AbstractClassWithJsonConverterAttribute
    {
        public string Prop3 { get; set; }
        public bool Prop4 { get; set; }

        private string typeIdentifier = "DerivedClass2";
        public override string TypeIdentifier
        {
            get
            {
                return typeIdentifier;
            }

            set
            {
                typeIdentifier = value;
            }
        }
    }

    [JsonConverter(typeof(BaseConverter))]
    public abstract class AbstractClassWithJsonConverterAttribute
    {

        public abstract string TypeIdentifier { get; set; }



        /// <summary>
        /// see http://stackoverflow.com/a/12641541
        /// </summary>
        private class BaseConverter : JsonCreationConverter<AbstractClassWithJsonConverterAttribute>
        {
            protected override AbstractClassWithJsonConverterAttribute Create(Type objectType,
          Newtonsoft.Json.Linq.JObject jObject)
            {
                //TODO: read the raw JSON object through jObject to identify the type
                //e.g. here I'm reading a 'TypeIdentifier' property:
                switch (jObject.Value<string>("TypeIdentifier"))
                {
                    case "DerivedClass1":
                        return new DerivedClass1();
                    case "DerivedClass2":
                        return new DerivedClass2();

                }
                throw new Exception("Couldnt find the right type to create, missing a proper TypeIdentifier on your JSON? missing a switch case?");

            }


        }
    }

    public abstract class JsonCreationConverter<T> : JsonConverter
    {
        /// <summary>
        /// this is very important, otherwise serialization breaks!
        /// </summary>
        public override bool CanWrite
        {
            get
            {
                return false;
            }
        }
        /// <summary> 
        /// Create an instance of objectType, based properties in the JSON object 
        /// </summary> 
        /// <param name="objectType">type of object expected</param> 
        /// <param name="jObject">contents of JSON object that will be 
        /// deserialized</param> 
        /// <returns></returns> 
        protected abstract T Create(Type objectType, JObject jObject);

        public override bool CanConvert(Type objectType)
        {
            return typeof(T).IsAssignableFrom(objectType);
        }

        public override object ReadJson(JsonReader reader, Type objectType,
          object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null)
                return null;
            // Load JObject from stream 
            JObject jObject = JObject.Load(reader);

            // Create target object based on JObject 
            T target = Create(objectType, jObject);

            // Populate the object properties 
            serializer.Populate(jObject.CreateReader(), target);

            return target;
        }

        public override void WriteJson(JsonWriter writer, object value,
          JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }
}
`

and an ugly test (that fails) that generates the schema in the same way I do it:
`  [Test] public void GenerateSchemaFromClassThatDerivesAbstractTypeWithCustomJsonConverter()
        {
            Newtonsoft.Json.Schema.Generation.JSchemaGenerator generator = new Newtonsoft.Json.Schema.Generation.JSchemaGenerator();
            generator.SchemaIdGenerationHandling = SchemaIdGenerationHandling.TypeName;

            JSchema schema = generator.Generate(typeof(DerivedClass1));
            Assert.Greater(schema.ToString().Length, 2);
        }`

**Comment by Vaevictus** [comment]
sorry I cant format that previous comment properly using code tags

**Comment by JamesNK** [comment]
Ah ok. I'm afraid I originally misunderstood your issue.

The reason that classes with a `JsonConverterAttribute` have a schema of {} is there is no way for the generator to know what JSON the converter could possibly write, so an empty schema - {} - is to allow anything.

If you want to have a schema for it then you could create an `JSchemaGenerationProvider` for that class and place the `JSchemaGenerationProviderAttribute` on the type.

**Comment by Vaevictus** [comment]
Hi James,

Thanks for the info. Since my JsonConverter specifies CanWrite as false, your generator could infer from this that your internal schema generator could work on it, no?

Alternatively, could you not expose your default newtonsoft.json.schema generator behaviour as something I can specify in the JSchemaGenerationProvider? At the moment it appears as the only JSchemaGenerationProvider I can specify out of your library is the enum handler one.

**Comment by Vaevictus** [comment]
Created pull request #55 for your consideration

**Comment by JamesNK** [comment]
Sounds like a reasonable solution. Done.

**Comment by JamesNK** [comment]
Now available - https://www.nuget.org/packages/Newtonsoft.Json.Schema/2.0.7
