### ISSUE TITLE
Selfreferencing external schema file throws exception

### ISSUE THREAD

**Issue by KaiTwiggy** [JamesNK/Newtonsoft.Json.Schema#52]
When i try to have a main schema which refers to a external schema that is inside a file everything works okay, but when that external schema has self reference then it is not handled correctly and throws an exception. I think this is because JSchemaReader.cs:894 doesn't check that the reference schema has subschema id present.

Here is test jsons from which the issue can be reproduced : 
**_test.schema.json:_**
```
{
  "id": "TestSchema",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "TestSchema",
  "description": "Test Schema for bug",
  "type": "object",
  "properties": {
    "Field1": {
      "description": "normal field",
      "type": "string"
    },
    "ReferenceArray": {
      "type": "array",
      "minimum": 1,
      "items": {
        "$ref": "testReferencedExternal.schema.json"
      }
    }
  }
}
```
**_testReferencedExternal.schema.json :_** 
```
{
    "id": "TestSchemaReference",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "TestSchemaReference",
    "description": "reference Test Schema for bug",
    "type": "object",
    "properties": {
        "ReferencedField": {
            "description": "normal field",
            "type": "string"
        },
        "SelfreferencedArray": {
            "type": "array",
            "minimum": 1,
            "items": {
                "$ref": "testReferencedExternal.schema.json"
            }
        }
    }
}
```

I've tried adding the check for the subschemaId to the if clause and it seems to work and no test seem to have failed. I'm not sure if that is the intent of the if clause but i deducted from the comments that this might be the case. As i'm not too familiar with the rest of the inner workings, i'm not sure if this has some side effects.

**Comment by JamesNK** [comment]
Thanks. Fixed!

**Comment by JamesNK** [comment]
Now available - https://www.nuget.org/packages/Newtonsoft.Json.Schema/2.0.7
