### ISSUE TITLE
How to validated pointer in json.net?

### ISSUE THREAD

**Issue by be4i** [JamesNK/Newtonsoft.Json.Schema#54]
Hello I have the following scenario:

JSON object: 

    {
    	"$id": "1",
        "someProp": "123",
    	"children": [{
    		"$id": "2",
    		"$type": "ClassB",
    		"Parent": {
    			"$ref": "1"
    		}
    	}]
    }

JSON schema :

    {
    	"id": "ClassA",
    	"required": true,
    	"type": [
    		"object",
    		"null"
    	],
    	"properties": {
    		"someProp": {
    			"required": true,
    			"type": [
    				"string",
    				"null"
    			]
    		},
    		"children": {
    			"id": "List<Child>",
    			"required": true,
    			"type": [
    				"array",
    				"null"
    			],
    			"items": {
    				"id": "Child",
    				"type": [
    					"object",
    					"null"
    				],
    				"properties": {
    					"id": {
    						"required": true,
    						"type": "integer"
    					},
    					"parent": {
    						"$ref": "ClassA"
    					}
    				}
    			}
    		}
    	}
    }

I have a complex object who has reference loops, so I have configured json.net to make reference when the object is serialized. Everything is working as expected I can serialize and deserialize the object, but when I am validating the JSON object with the above schema I got the following error : 

> Required properties are missing from object : "someProp", path :
> object.Children[0].parent

And that is correct how can make the schema look at the reference JSON object ?

**Comment by JamesNK** [comment]
Hi

You would have to modify your schema to have a oneOf, with the choices either being your object schema or an schema for the `{ "$ref": "id" }`

**Comment by be4i** [comment]
Hi,

thanks for your response can you please make a example with the scenario i have posted.

**Comment by JamesNK** [comment]
Here is an example of a oneOf

```
{
  "id": "ClassA",
  "required": true,
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "someProp": {
      "oneOf": [
        {
           /* your schema*/
        },
        {
          "type": "object",
          "properties": {
            "$ref": {
              "type": "string"
            }
          },
          "required": [
            "$ref"
          ]
        }
      ]
    },
    "children": {
      "id": "List<Child>",
      "required": true,
      "type": [
        "array",
        "null"
      ],
      "items": {
        "id": "Child",
        "type": [
          "object",
          "null"
        ],
        "properties": {
          "id": {
            "required": true,
            "type": "integer"
          },
          "parent": {
            "$ref": "ClassA"
          }
        }
      }
    }
  }
}
```
