### ISSUE TITLE
Circular Reference in JSON Schema Generation

### ISSUE THREAD

**Issue by dagrooms52** [JamesNK/Newtonsoft.Json.Schema#59]
Using the JSON Schema generator to generate a fairly large and complex object model with `SchemaLocationHandling` set to `Definitions` causes what seem to be circular references to be generated, and validation using this schema fails, giving a `JSchemaReaderException`. Generating the same schema with `SchemaLocationHandling` set to `Inline` clears the problem, and validation using this schema succeeds out of the box.
Is the intended use of the `Definitions` option for the developer to go in after generating and add external references to these schemas, or is this truly a bug?

**Comment by JamesNK** [comment]
Hi

I would need to see an example of the issue to know more
