### ISSUE TITLE
relative paths and definitions

### ISSUE THREAD

**Issue by krisrok** [JamesNK/Newtonsoft.Json.Schema#6]
to support relative reference paths like `{ "$ref": "foo.schema.json" }` i had to write a custom JSchemaResolver. by that the parser lost the ability to resolve references to internal definitions like `{ "$ref": "#/definitions/bar" }` : they are routed through my custom resolver, too.

so do i have to write a custom implementation to support absolute, relative and internal references or is there another way?

i think all that should be handled by the framework. or at least the user should be able to compose a resolver without losing features.

**Comment by JamesNK** [comment]
If you return null from GetSchema then relative internal references will still be resolved. I'll add a note to the documentation to say this.

**Comment by krisrok** [comment]
my bad, thanks!

**Comment by JamesNK** [comment]
Relative references are now supported without custom code: http://www.newtonsoft.com/jsonschema/help/html/JsonUrlSchemaResolverRelative.htm

**Comment by krisrok** [comment]
very nice indeed
