### ISSUE TITLE
Could not load type 'Newtonsoft.Json.Schema.JSchemaGenerator' 

### ISSUE THREAD

**Issue by shawnarvin** [JamesNK/Newtonsoft.Json.Schema#61]
Hi,
Getting this error with version v2.0.7. Using this with Newtonsoft.Json version v9.0.1. 

Could not load type 'Newtonsoft.Json.Schema.JSchemaGenerator' from assembly 'Newtonsoft.Json.Schema, Version=2.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

**Comment by JamesNK** [comment]
You must be referencing different versions of the assembly. `JSchemaGenerator` was moved to the `Newtonsoft.Json.Schema.Generation` namespace in V2.
