### ISSUE TITLE
JSchema generation of Dictionaries Not Usable

### ISSUE THREAD

**Issue by dagrooms52** [JamesNK/Newtonsoft.Json.Schema#62]
I'm using the JSchema generator to generate a class with a Dictionary member. The resulting schema does not give enough type information to show what the original types of the Dictionary were. 

My JSchema generator is initialized as follows:

    var generator = new JSchemaGenerator
    {
        GenerationProviders = { new StringEnumGenerationProvider() },
        SchemaIdGenerationHandling = SchemaIdGenerationHandling.TypeName,
        SchemaLocationHandling = SchemaLocationHandling.Inline
    };

For the following class:

    internal class DictionaryTester
    {
        public Dictionary<string, string> StringToString { get; set; }

        public Dictionary<string, int> StringToInt { get; set; }

        public Dictionary<int, int> IntToInt { get; set; }
    }

I get the following JSchema:

    {{
    "id": "DictionaryTester",
    "type": "object",
    "properties": {
        "StringToString": {
        "type": [
            "object",
            "null"
        ],
        "additionalProperties": {
            "type": [
            "string",
            "null"
            ]
        }
        },
        "StringToInt": {
        "type": [
            "object",
            "null"
        ],
        "additionalProperties": {
            "type": "integer"
        }
        },
        "IntToInt": {
        "type": [
            "object",
            "null"
        ],
        "additionalProperties": {
            "type": "integer"
        }
        }
    },
    "required": [
        "StringToString",
        "StringToInt",
        "IntToInt"
    ]
    }}

As you can see, the type of the key is lost in Dictionary generation, and the value type is shown in "additionalProperties." From [this StackOverflow answer](http://stackoverflow.com/questions/27357861/dictionary-like-json-schema) it seems that additionalProperties should be used to define the schema of the dictionary, but I'm wondering if there is anything in the JSON Schema spec about doing so anonymously (without naming the properties), since a dictionary in JSON is the same as an object. Is it intentional to leave out the key's type when working with Dictionaries?

**Comment by JamesNK** [comment]
The key in JSON is always a string. Remember that `Dictionary<int, int>` serializes as `{ "1": 1 }`.

One potential solution is using patternProperties. In it you can supply a regex that constrains properties to a regular expression. JSchemaGenerator doesn't use it because a different regular expression would be required for each, i.e. one each for integers, floating point numbers, dates, GUIDs, booleans, etc.

**Comment by dagrooms52** [comment]
Thanks for your help, I assumed the key would be a string but wanted to do some further playing around with the Schema generator. I found that when a dictionary with complex object keys is made, the schema generator produces the following schema:

    "KeyToString": {
      "type": [
        "object",
        "null"
      ]
    }

from a `Dictionary<Key, string>` where `Key` is a class with one `string` and one `int` property.

From the previous schema generations I would expect this to assume that the string is a key, which I can only assume it does since there is no type information (as before, we knew that). But this schema does not add the type "string" to "additionalProperties". I realize this is just a limitation of JSON, so a List<KeyValuePair> will probably serve as a better model.
