### ISSUE TITLE
Schema generation - Add Format customization

### ISSUE THREAD

**Issue by payoff** [JamesNK/Newtonsoft.Json.Schema#7]
The only way to generate a schema "format" is to use DataAnnotation:
schema.Format = DataAnnotationHelpers.GetFormat(memberProperty);

Json Schema should allow to customize format and produce something like:
https://developers.google.com/discovery/v1/type-format
or: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types

ex:     "Long": {
      "type": "integer",
      "format": "int64"
    },

Mic.

**Comment by JamesNK** [comment]
I think you could achieve that today by creating a JSchemaGenerationProvider and adding the format manually for those types. That would be a little annoying to do though. Are you interested in being able to add any format or do you just want the formats listed in your links?

Note that the schema validator itself wouldn't use those non-standard formats. Is that important to you?

**Comment by payoff** [comment]
The quick & dirty answer is yes to both.
I've seen the JSchemaGenerationProvider  but I discarded immediately that way.

I think that a refactoring can be done in this way:
Add a IList<JFormatProvider> FormatProviders to JSchemaGenerator.

Create a JFormatProvider like this:
    public abstract class JFormatProvider
    {
       // tell you if can be used with current content item
        public abstract bool CanBeUsedWith(JSchemaTypeGenerationContext context);
        // generate the format
        public abstract string GetFormat(JsonProperty context);
        // check validity
        public abstract bool Validate(string format);
    }
CanBeUsedWith tells you if it can be used when you add Format in PopulateSchema, if so you can call GetFormat.
The validate contains the code that check if this is valid, when you validate.

You can split all the logic of DataAnnotationHelpers.GetFormat in JFormatProvider like:
UriFormatDataAnnotationsProvider,
PhoneFormatDataAnnotationsProvider,
and user can add new custom implementation or remove default implementation that need to be customized.

**Comment by JamesNK** [comment]
That sounds like overkill for a niche feature

I created a sample to include in the documentation of using a provider. Source is here: https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/e88576c0b447a7a59206c4159bd6647e7ff0d946/Src/Newtonsoft.Json.Schema.Tests/Documentation/Samples/Generation/CreateCustomProvider.cs

I'll think about how to support using custom formats during validation. For now they won't be used.

**Comment by JamesNK** [comment]
I've added documentation here for how to customize format with a schema generation provider: http://www.newtonsoft.com/jsonschema/help/html/CreateCustomProvider.htm
