### ISSUE TITLE
JSchema serialization adds /0 to path and deserialization fails

### ISSUE THREAD

**Issue by FishDawg** [JamesNK/Newtonsoft.Json.Schema#78]
I load a schema with JSchema.Parse successfully. Then I serialize it to a string with JSchema.ToString and try to load it again. Now it fails with a JSchemaReaderException. I see that JSchema.ToString has added a "/0" to some $ref paths, which makes them invalid paths. Below is simplified repro code and the exception details.

Code:

    var json = "{\r\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\r\n  \"id\": \"MySchema\",\r\n  \"$type\": \"schema\",\r\n  \"definitions\": {\r\n    \"myDefinition\": {\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"items\": {\r\n          \"type\": \"object\",\r\n          \"properties\": {\r\n            \"value\": {\r\n              \"type\": \"array\",\r\n              \"items\": {\r\n                \"oneOf\": [\r\n                  {\r\n                    \"$ref\": \"MySchema#/definitions/myDefinition/properties/items/properties/value\"\r\n                  },\r\n                  {\r\n                    \"$ref\": \"MySchema#/definitions/myDefinition\"\r\n                  }\r\n                ]\r\n              }\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"allOf\": [\r\n    {\r\n      \"properties\": {\r\n        \"myProperty\": {\r\n          \"$ref\": \"MySchema#/definitions/myDefinition/properties/items/properties/value\"\r\n        }\r\n      }\r\n    }\r\n  ]\r\n}";
    var schema = JSchema.Parse(json);
    json = schema.ToString();
    schema = JSchema.Parse(json);

Exception:

    Newtonsoft.Json.Schema.JSchemaReaderException occurred
    HResult=-2146233088
    LineNumber=43
    LinePosition=23
    Message=Could not resolve schema reference 'MySchema#/definitions/myDefinition/properties/items/properties/value/items/0/oneOf/0'. Path 'allOf[0].properties.myProperty', line 43, position 23.
    Path=allOf[0].properties.myProperty
    Source=Newtonsoft.Json.Schema
    StackTrace:
       at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchema(DeferedSchema deferedSchema)
       at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchemas()
       at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader, Boolean resolveDeferedSchemas)
       at Newtonsoft.Json.Schema.JSchema.Load(JsonReader reader, JSchemaReaderSettings settings)
       at Newtonsoft.Json.Schema.JSchema.Parse(String json, JSchemaReaderSettings settings)
       at Newtonsoft.Json.Schema.JSchema.Parse(String json)
       at JSchemaTest.Program.Main() in D:\Visual Studio 2015\Projects\JSchemaTest\Program.cs:line 19

**Comment by JamesNK** [comment]
Thanks for the example. Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/0f12bdc3373be58f6f8785b9ea7b41ced1f05f19

Is this bug blocking you or is it just something you noticed? I'd like to know whether a new version should be released.

**Comment by FishDawg** [comment]
Thank you for the fast fix. This issue is not blocking me.
