### ISSUE TITLE
Bug in JsonSchemaBuild.ProcessSchemaProperties

### ISSUE THREAD

**Issue by PDIBWade** [JamesNK/Newtonsoft.Json.Schema#8]
The handling for the "required" tagname accommodates only the use of the "required" keyword on a specific property.  It assumes the associated value is a Boolean.

case JsonSchemaConstants.RequiredPropertyName:
                        CurrentSchema.Required = (bool)property.Value;
                        break;

When a required properties array is encountered, it throws an exception.
e.g.:
this works:
"properties":{"Key":{"type":"string","required":true},"Value":{"type":"string"}}

and this triggers an ArgumentException("Can not convert {0} to Boolean.") from JToken:
"properties":{"Key":{"type":"string"},"Value":{"type":"string"}},
"required":["Key"]

**Comment by JamesNK** [comment]
That is the old version of Json.NET Schema which is no longer updated. If you want Draft V4 support download this: https://www.nuget.org/packages/Newtonsoft.Json.Schema
