### ISSUE TITLE
Error after upgrade of Json.net to 10

### ISSUE THREAD

**Issue by dmikov** [JamesNK/Newtonsoft.Json.Schema#80]
Works fine with 9.0.1 Json.net, but after upgrade to 10.0.1 gives this error on Generate method call
```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Newtonsoft.Json.Serialization.IContractResolver Newtonsoft.Json.Serialization.DefaultContractResolver.get_Instance()'.
  Source=<Cannot evaluate the exception source>
```

**Comment by JamesNK** [comment]
Whoops!

I've released a new version that should fix this - https://www.nuget.org/packages/Newtonsoft.Json.Schema/2.0.9

Let me know if it doesn't work for you.
