### ISSUE TITLE
LicenseHelpers doesn't dispose the streams after deserialization

### ISSUE THREAD

**Issue by jkanczler** [JamesNK/Newtonsoft.Json.Schema#82]
RegisterLicense method of the LicenseHelpers doesn't dispose the memory stream that is created, it can cause memory leak, though we know it's minor leak.

**Comment by JamesNK** [comment]
Do you know what type is being leaked? Is it a permanent leak or does it get cleaned up when a finalizer is run?

**Comment by jkanczler** [comment]
In the LicenseHelpers.cs at line 140:
MemoryStream ms = new MemoryStream(licenseData, 128, licenseData.Length - 128);

This memory stream won't be disposed.

**Comment by jkanczler** [comment]
```
            MemoryStream ms = new MemoryStream(licenseData, 128, licenseData.Length - 128);
            JsonSerializer serializer = new JsonSerializer();

            LicenseDetails deserializedLicense = serializer.Deserialize<LicenseDetails>(new JsonTextReader(new StreamReader(ms)));
```

Actually to be safe, JsonTextReader and StreamReader should be disposed too.

**Comment by JamesNK** [comment]
Disposing a MemoryStream doesn't really do anything other than prevent you from using it anymore. Its memory gets cleaned up when the MemoryStream is cleaned up.

However there are some unmanaged RSA and SHA1 objects that should be disposed.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/cb03549030f035a3f5a536dbe73955f4f8d12a93
