### ISSUE TITLE
Named Enumerations

### ISSUE THREAD

**Issue by vinaysharma77** [JamesNK/Newtonsoft.Json.Schema#83]
Hello,

I'm running into a challenge in serializing the named enumerations when using Newtonsoft.Json.Schema for serializing my POCO.. Is it possible to associate any additional information with each enum value..? This article in json-schema-org github talks more in detail about the issue. 

https://github.com/json-schema-org/json-schema-spec/issues/57

The proposed solution there is to add "Constant" property at the schema level to handle this scenario. 

Any plans of incorporating this in JSchema class in near future?

Thanks,
Vin

**Comment by JamesNK** [comment]
When V6 is finalized and approved that feature will be added. I don't know when that will be.

**Comment by knuxbbs** [comment]
@JamesNK there is any guide about this?
