### ISSUE TITLE
Json.Net 9.0.0 reference

### ISSUE THREAD

**Issue by AlessandroP8** [JamesNK/Newtonsoft.Json.Schema#84]
Hi,
the current version of Json Schema references Json.Net 9.0.0.
In a project where I use both, I can rebind the 9.0.0 referecence to the latest (10.0.1) version of Json.net using the bindingRedirect in app.config.
But in a scenario where both are used in a .vsx Visual Studio extension, I cannot specify any custom bindings (the extension run in the devenv.exe process).
Can you upgrade Json.Net reference to the 10.0.0 version ?

Thanks

**Comment by JamesNK** [comment]
Done - https://github.com/JamesNK/Newtonsoft.Json.Schema/releases/tag/2.0.11

Let me know if you have any issues after updating.

**Comment by AlessandroP8** [comment]
Thanks !

2017-04-12 11:29 GMT+02:00 James Newton-King <notifications@github.com>:
