### ISSUE TITLE
Json schema "format" for Guids and DateTime is not populated

### ISSUE THREAD

**Issue by lennygran** [JamesNK/Newtonsoft.Json.Schema#86]
An appropriate "format" for properties of type Guid, DateTime, Decimal do not automatically populated. E.g. property `public Guid AccountId { get; set; }` should produce:
```
 "accountId": {
      "type": "string",
      "format": "guid"
},
```
but produces:
```
 "accountId": {
      "type": "string"
},
```

**Comment by JamesNK** [comment]
There is no known "guid" format, here is the predefined formats: http://json-schema.org/latest/json-schema-validation.html#rfc.section.7

Making DateTime, DateTimeOffset and Uri include a format makes sense.

You could write a JSchemaGenerationProvider to include a format with Guid values.

**Comment by lennygran** [comment]
Hi James,
Yes, I fully understand that custom handling can be implemented, but built-in with consistent handling of all other attributes is preferred. This is the reason I asked. Although it's not defined by the standard, the "guid" is widely accepted way of depict the Guid string format. But, I hear and respect your opinion, therefore limiting implementation to already standardized items only makes sense.
Best regards,
Lenny

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/9416701fe5109a3ac7ebc54edfafa05f9428ab67

**Comment by lennygran** [comment]
I wouldn't consider this "Done" though - at least for already defined formats, library does not support them as of today. It is certainly your choice, but probably not the best way to handle GIT library, especially that asks for license. Can be handled better.

**Comment by JamesNK** [comment]
Pardon? Json.NET Schema will validate all the defined formats.

There is no spec for how to generate a JSON Schema from .NET types. Json.NET Schema adds all the information that it can, and if you want more then you can write a `JSchemaGenerationProvider`.

**Comment by lennygran** [comment]
I guess it is a difference of opinions. Why would I want to generate something that I cannot validate due to lack of info in the schema? But that's OK, all I know that I'll use another available alternative. You just lost $999, not sure if it's matter much.

Same is applicable to https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/87.

**Comment by JamesNK** [comment]
No validator will validate `format: "guid"` by default because it is not a [known format defined in the spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7).

If you want to include a custom format then use a custom `JSchemaGenerationProvider` like so - http://www.newtonsoft.com/jsonschema/help/html/CreateCustomProvider.htm

And validate it with a custom `JsonValidator` rule like so - http://www.newtonsoft.com/jsonschema/help/html/CustomJsonValidator.htm
