### ISSUE TITLE
Description attribute is not populated

### ISSUE THREAD

**Issue by lennygran** [JamesNK/Newtonsoft.Json.Schema#87]
The "description" schema attribute is not populated for properties. Neither `System.ComponentModel.DataAnnotations.DisplayAttribute`, nor `System.ComponentModel.DescriptionAttribute` are being processed.

E.g. 
```
[DataMember]
[Description("Gets or sets the id.")]
public Guid Id { get; set; }
```
suppose to produce:
```
    "id": {
      "type": "string",
      "description": "Gets or sets the id."
    },
```
but creates:
```
    "id": {
      "type": "string"
    },
```

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/a9084e034e3bc65bfc33d3be8dc309694f438d6f
