### ISSUE TITLE
Don't by default make all properties required using JSchemaGenerator over a type

### ISSUE THREAD

**Issue by williamwsmith** [JamesNK/Newtonsoft.Json.Schema#9]
This is overly restrictive as the default case since many times JSON will be sparse compared to the POCO you are serializing against.  Since you do all using data annotation attribute [Required]  the default should NOT required.  Thanks for the work on this project.

**Comment by JamesNK** [comment]
"Don't by default make all properties required using JSchemaGenerator over a type"

Pardon? I don't understand what you're asking.

**Comment by fastwit** [comment]
I'm facing the same issue here is the test case:

        [TestFixture]
        public class PropertiesAlwaysRequiredTest
        {
            public class IssueModel
            {
                public int IssueId { get; set; }//default is 0 and it is ok
                public string Title { get; set; }
                public string Description { get; set; }
                public object OptionalProperty { get; set; }
                public int? NotUsedInt { get; set; }
            }

            [Test]
            public void Test()
            {
                var schemaGenerator = new JSchemaGenerator();
                var jsonSchema = schemaGenerator.Generate(typeof(IssueModel));

                Console.WriteLine(jsonSchema.Required.Aggregate((a,b)=>a+","+b));

                Assert.AreEqual(0, jsonSchema.Required.Count);
            }
        }

**Comment by stuartajames** [comment]
I think he mean what https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/15 is asking for, 

that properties should default to not required.

**Comment by JamesNK** [comment]
The next release will have a DefaultRequired property that will specify whether properties are required. I'll put a comment here when it is available.
