### ISSUE TITLE
Title/Description Not Set When Using StringEnumGenerationProvider

### ISSUE THREAD

**Issue by gwilliams** [JamesNK/Newtonsoft.Json.Schema#92]
When adding the StringEnumGenerationProvider, any [DisplayName] or [Description] attributes are ignored for enum types.

Excluding the StringEnumGenerationProvider however will populate the Title/Description properties if the attributes are set.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/5dbc91e9901264add05c64ae111c472ca81ed925
