### ISSUE TITLE
Consume System.ComponentModel.DataAnnotations.DisplayAttribute if present

### ISSUE THREAD

**Issue by cervengoc** [JamesNK/Newtonsoft.Json.Schema#93]
Hi, first of all thanks for the great work what you're constantly putting into Json.NET.

I'd like to suggest implementing the usage of the mentioned attribute for populating the `Title` and `Description` info of a property schema. 

About priority, I see that now the predecessor attributes are supported, `DisplayNameAttribute` and `DescriptionAttribute`.  If a `DisplayAttribute` is present, it should be favored instead of these attributes, however, the support should be still kept of course for legacy. 

I'd be happy to create this little PR, but unfortunately I won't have a VS2017 environment in the near-future, so it would be great if you could add it.

**Comment by JamesNK** [comment]
Done - https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/9e0f4db6c43d47ccaf24f4f5e1e3bf7055474eeb

Thanks for the suggestion
