### ISSUE TITLE
Range-Annotation .ToString() Bug

### ISSUE THREAD

**Issue by bbelius** [JamesNK/Newtonsoft.Json.Schema#95]
When calling .ToString() on an JSchema the range annotation`[Range(0,1000)]` will be rendered as
```json
"ImAnObject": {
          "type": "integer",
          "minimum": 1.0,
          "minimum": 1000.0
        },
```

This bug will not appear if you set the SchemaVersion.Draft4:
```cs
.ToString(SchemaVersion.Draft4)
```

Reason for this may be a copy-paste bug at line 334 in `Newtonsoft.Json.Schema/Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs`
```cs
if (EnsureVersion(SchemaVersion.Draft6))
{
/*line333*/ WritePropertyIfNotNull(_writer, schema.ExclusiveMinimum ? Constants.PropertyNames.ExclusiveMinimum : Constants.PropertyNames.Minimum, schema.Minimum);
/*line334*/ WritePropertyIfNotNull(_writer, schema.ExclusiveMaximum ? Constants.PropertyNames.ExclusiveMaximum : Constants.PropertyNames.Minimum, schema.Maximum); 
   // : Constants.PropertyNames.Minimum should be : Constants.PropertyNames.Maximum
}
```

**Comment by JamesNK** [comment]
Good catch

Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/b832b1f8e2e2023d42742a3ac7ecf8a9f14463c3

**Comment by JamesNK** [comment]
Fix is available on NuGet https://github.com/JamesNK/Newtonsoft.Json.Schema/releases/tag/3.0.2
