### ISSUE TITLE
Can't parse example from specification

### ISSUE THREAD

**Issue by chandrush** [JamesNK/Newtonsoft.Json.Schema#96]
Hello!
I tried to parse an example from JSON Schema specification and got failed with the message:

Newtonsoft.Json.Schema.JSchemaReaderException : Could not resolve schema reference 'http://example.net/root.json#item'. Path 'items.items', line 5, position 18.

An example is from the http://json-schema.org/latest/json-schema-core.html#rfc.section.9.2.1
`{
    "$id": "http://example.net/root.json",
    "items": {
        "type": "array",
        "items": { "$ref": "#item" }
    },
    "definitions": {
        "single": {
            "$id": "#item",
            "type": "integer"
        }
    }
}`

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/b970c072371fb872402aff768668c58c655733fa
