### ISSUE TITLE
Newtonsoft.Json.Schema.JSchemaReaderException: 'Could not resolve schema reference 'X'. Path 'Y'

### ISSUE THREAD

**Issue by cse-sramos** [JamesNK/Newtonsoft.Json.Schema#98]
Hello,

My company recently purchased the latest version (30.2) JSchema license and there is one issue we encountered. The issue is when you have a complex object that utilizes Json attributes (such as **JsonObjectAttribute** and **JsonPropertyAttribute**) and some types are used at different levels in the complex object to generate a json schema off of it. The JSchema can be created and we can get its string representation using **schema.ToString(SchemaVersion.Draft4)**.

We'd like to save that json schema in string format for later use. The issue comes when we want to parse the json schema utilizing **JSchema.Parse(schemaString)** that it was created previously. We get the exception **Newtonsoft.Json.Schema.JSchemaReaderException: 'Could not resolve schema reference 'X'. Path 'Y'**

I've attached a test project sample of this issue.
[JsonSchema.zip](https://github.com/JamesNK/Newtonsoft.Json.Schema/files/1178334/JsonSchema.zip)

You're help will be appreciated!

Thank you

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/dca977705701b51dca2a484ad5f424bacd165f50

Is the blocking you? Do you need the fix now or can you wait for a future release?

**Comment by cse-sramos** [comment]
Thank you very much for working on this matter JamesNK. For now, I implemented a temporary workaround. We are looking forward to releasing a few important improvements we made to our APIs' Architecture at Cisco utilizing this awesome Json Schema Validation mechanism. We really want to release these enhancements without the workaround. When will it be the next release?

Thank you!

**Comment by JamesNK** [comment]
Hi

3.0.3 includes a fix for your bug https://www.nuget.org/packages/Newtonsoft.Json.Schema/3.0.3
